<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.4">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2025-05-14">

<title>camilleri_larrick_2019_supp – Energy AI Study</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-19cd9126a9a9c64aacb03dc90954a64a.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-ed05bc920637904bee9c30014c322b6c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../assets/purdue.scss">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Energy AI Study</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../task.html"> 
<span class="menu-text">Task</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../inspector.html"> 
<span class="menu-text">Item_Inspector</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../survey_dash.html"> 
<span class="menu-text">Dash</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../proposals/prop_slides.html"> 
<span class="menu-text">Slides</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/tegorman13/llm_energy_task"> <i class="bi bi-github" role="img" aria-label="github">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#supplementary-information" id="toc-supplementary-information" class="nav-link active" data-scroll-target="#supplementary-information">Supplementary Information</a>
  <ul class="collapse">
  <li><a href="#supplementary-note-1-studies-1a-and-1b-stimuli" id="toc-supplementary-note-1-studies-1a-and-1b-stimuli" class="nav-link" data-scroll-target="#supplementary-note-1-studies-1a-and-1b-stimuli">Supplementary Note 1: Studies 1A and 1B Stimuli</a></li>
  <li><a href="#supplementary-note-2-studies-1c-and-1d---sensitivity-of-results-to-reference-unit" id="toc-supplementary-note-2-studies-1c-and-1d---sensitivity-of-results-to-reference-unit" class="nav-link" data-scroll-target="#supplementary-note-2-studies-1c-and-1d---sensitivity-of-results-to-reference-unit">Supplementary Note 2: Studies 1C and 1D - Sensitivity of Results to Reference Unit</a></li>
  <li><a href="#supplementary-note-3-actual-life-cycle-energy-use-and-ghg-emissions-for-different-types-of-food-and-appliances" id="toc-supplementary-note-3-actual-life-cycle-energy-use-and-ghg-emissions-for-different-types-of-food-and-appliances" class="nav-link" data-scroll-target="#supplementary-note-3-actual-life-cycle-energy-use-and-ghg-emissions-for-different-types-of-food-and-appliances">Supplementary Note 3: Actual Life-Cycle Energy Use and GHG Emissions for Different Types of Food and Appliances</a></li>
  <li><a href="#supplementary-note-4-studies-1a-and-1b---testing-additional-covariates-and-sensitivity-of-results-to-assumed-actual-values" id="toc-supplementary-note-4-studies-1a-and-1b---testing-additional-covariates-and-sensitivity-of-results-to-assumed-actual-values" class="nav-link" data-scroll-target="#supplementary-note-4-studies-1a-and-1b---testing-additional-covariates-and-sensitivity-of-results-to-assumed-actual-values">Supplementary Note 4: Studies 1A and 1B - Testing Additional Covariates and Sensitivity of Results to Assumed Actual Values</a></li>
  <li><a href="#supplementary-note-5-study-2-stimuli" id="toc-supplementary-note-5-study-2-stimuli" class="nav-link" data-scroll-target="#supplementary-note-5-study-2-stimuli">Supplementary Note 5: Study 2 Stimuli</a></li>
  <li><a href="#supplementary-note-6-study-2---additional-analyses" id="toc-supplementary-note-6-study-2---additional-analyses" class="nav-link" data-scroll-target="#supplementary-note-6-study-2---additional-analyses">Supplementary Note 6: Study 2 - Additional Analyses</a></li>
  <li><a href="#supplementary-note-7-actual-life-cycle-ghg-emissions-for-a-range-of-prepared-soups" id="toc-supplementary-note-7-actual-life-cycle-ghg-emissions-for-a-range-of-prepared-soups" class="nav-link" data-scroll-target="#supplementary-note-7-actual-life-cycle-ghg-emissions-for-a-range-of-prepared-soups">Supplementary Note 7: Actual Life-Cycle GHG Emissions for a Range of Prepared Soups</a></li>
  <li><a href="#references-supplementary-material" id="toc-references-supplementary-material" class="nav-link" data-scroll-target="#references-supplementary-material">References (Supplementary Material)</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content column-page-left" id="quarto-document-content"><div class="quarto-title-block"><div class="quarto-title-tools-only"><h1></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
</div>



<div class="quarto-title-meta column-page-left">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 14, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="supplementary-information" class="level2">
<h2 class="anchored" data-anchor-id="supplementary-information">Supplementary Information</h2>
<p>Camilleri, A. R., Larrick, R. P., Hossain, S., &amp; Patino-Echeverri, D. (2019). Consumers underestimate the emissions associated with food but are aided by labels. Nature Climate Change, 9(1), 53–58. https://doi.org/10.1038/s41558-018-0354-z</p>
<section id="supplementary-note-1-studies-1a-and-1b-stimuli" class="level3">
<h3 class="anchored" data-anchor-id="supplementary-note-1-studies-1a-and-1b-stimuli">Supplementary Note 1: Studies 1A and 1B Stimuli</h3>
<p><strong>Study 1A Stimuli:</strong></p>
<p><em>Page 1: Sampling Quota Questions</em></p>
<p>What is your gender? * Man * Woman</p>
<p>What age group do you fall in? * Under 18 * 18-24 * 25-34 * 35-44 * 45-54 * 55+</p>
<p>What is your ethnicity? * White * African American * Asian * Hispanic * Other</p>
<p><em>Page 2: Estimate of Household Energy Consumption</em></p>
<p>Please answer the following using only prior knowledge. Think about an average household in the United States. Now think about the total amount of energy that is used directly by that household in one year. Consider that the energy used by a household can be divided into: * Household operations: electricity, natural gas, and heating oil that is used for the house * Transportation: air travel, motor travel, and public transportation used by people in the household * Food production: growing and shipping food that people in the household eat.</p>
<p>What percentage of the total energy consumed per year by an average household in the United States is attributed to each of the following categories? * % household operations: [slider bar response option ranging between 0 and 100] * % transportation: [slider bar response option ranging between 0 and 100] * % food production: [slider bar response option ranging between 0 and 100]</p>
<p><em>Page 3: Appliance Energy Consumption</em></p>
<p>Using a 100-watt incandescent light bulb for one hour consumes 100 units of energy. Using this scale, how many units of energy do you think each of the following devices typically consumes when in use for one hour? Enter a number less than 100 if you think the device consumes less energy than using a 100-watt bulb for an hour. Enter a number greater than 100 if you think the device consumes more energy than using a 100-watt bulb for an hour. For example, using two 100-watt incandescent bulbs for an hour would consume 200 units of energy. Your best estimates are fine. Please enter whole numbers with no other text (no decimals, ranges, or percent signs). Please respond carefully and thoughtfully (i.e., don’t just put the same number for each item). If you do not answer carefully, your responses may be considered invalid.</p>
<ul>
<li>Units of energy for: A compact fluorescent light bulb that is as bright as a 100-watt incandescent light bulb</li>
<li>Units of energy for: A desktop computer (including monitor)</li>
<li>Units of energy for: A laptop computer</li>
<li>Units of energy for: An electric clothes dryer</li>
<li>Units of energy for: A handheld clothes iron</li>
<li>Units of energy for: A washing machine (excluding water)</li>
<li>Units of energy for: A portable electric heater</li>
<li>Units of energy for: A room air-conditioner</li>
<li>Units of energy for: A central air-conditioner</li>
<li>Units of energy for: A coffee maker</li>
<li>Units of energy for: A dishwasher</li>
<li>Units of energy for: A freezer</li>
<li>Units of energy for: A refrigerator</li>
<li>Units of energy for: A toaster oven</li>
<li>Units of energy for: A microwave oven</li>
<li>Units of energy for: A television</li>
<li>Units of energy for: A vacuum cleaner</li>
<li>Units of energy for: A DVD player</li>
<li>Units of energy for: Enter the number 100 in this box</li>
</ul>
<p><em>Page 4: Food Energy Consumption</em></p>
<p>Using a 100-watt incandescent light bulb for one hour consumes 100 units of energy. Using this scale, how many units of energy do you think each of the following foods consumes to produce and transport? Enter a number less than 100 if you think the food’s production and transport consumes less energy than using a 100-watt bulb for an hour. Enter a number greater than 100 if you think the food’s production and transport consumes more energy than using a 100-watt bulb for an hour. For example, using two 100-watt incandescent bulbs for an hour would consume 200 units of energy. Your best estimates are fine. Please enter whole numbers with no other text (no decimals, ranges, or percent signs). Please respond carefully and thoughtfully (i.e., don’t just put the same number for each item). If you do not answer carefully, your responses may be considered invalid.</p>
<ul>
<li>Units of energy for: 1 small fist of lamb (0.22 lb)</li>
<li>Units of energy for: 1 small fist of beef (0.22 lb)</li>
<li>Units of energy for: 1 small fist of pork (0.22 lb)</li>
<li>Units of energy for: 2 slices of cheese (0.12 lb)</li>
<li>Units of energy for: 1 cup of milk (0.54 lb)</li>
<li>Units of energy for: 1 tofu steak (0.38 lb)</li>
<li>Units of energy for: A handful of almonds (0.16 lb)</li>
<li>Units of energy for: 2 large eggs (0.22 lb)</li>
<li>Units of energy for: 1 medium-sized potato (0.47 lb)</li>
<li>Units of energy for: 1 medium-sized apple (0.40 lb)</li>
<li>Units of energy for: 1 medium-sized orange (0.31 lb)</li>
<li>Units of energy for: 1 medium-sized tomato (0.27 lb)</li>
<li>Units of energy for: A handful of walnuts (0.14 lb)</li>
<li>Units of energy for: Half a cup of beans (0.20 lb)</li>
<li>Units of energy for: Half a cup of rice (0.20 lb)</li>
<li>Units of energy for: Half a cup of wheat (0.21 lb)</li>
<li>Units of energy for: Half a cup of barley (0.22 lb)</li>
<li>Units of energy for: Half a cup of soybeans (0.28 lb)</li>
<li>Units of energy for: Half a cup of maize / corn (0.16 lb)</li>
<li>Units of energy for: Enter the number 100 in this box</li>
</ul>
<p>Notes: * Foods are listed as their approximate serving size. * Energy used includes production and transport from US manufacturer to distributor only and is based on an average distance of 1,500 miles travelled by a semi-trailer truck. * Energy from further processing, transport between distributor and retailer, consumption, and disposal are not included.</p>
<p><em>Page 5: Attention Check Questions</em></p>
<p>How many miles do you assume food is transported on average between manufacturer (e.g., farm) and distributor? ____ According to the information on the previous page, how many units of energy are consumed by using a 100-watt incandescent light bulb for one hour? * 100 units * 500 units * 120 units * 80 units</p>
<p><em>Page 6: Environmental Worldview</em> [NEPr Scale questions listed - omitted here for brevity, standard 15 items]</p>
<p><em>Page 7: Demographics</em> [Standard demographic questions: Age, Education, Employment Status, Household Income, Political Orientation (Economic &amp; Social), Political Affiliation - omitted here for brevity]</p>
<p><em>Page 8: Conclusion</em> Thank you for your participation! If you have any reactions, comments, suggestions, hated some things, loved some things, or have spotted any problems with the questionnaire, then please provide them below. We really do value your feedback! ____</p>
<hr>
<p><strong>Study 1B Stimuli:</strong></p>
<p><em>Pages 1 &amp; 2: Sampling Quota Questions and Estimate of Household GHG Emissions Source</em> [Identical to Study 1A, asking about GHG emissions instead of energy consumption]</p>
<p><em>Page 3: Appliance GHG Emissions</em> Using a 100-watt incandescent light bulb for one hour emits 100 units of greenhouse gas emissions. Using this scale, how many units of greenhouse gas emissions do you think each of the following devices typically emits when in use for one hour? [Instructions similar to Study 1A, asking for GHG units] [List of 18 appliances, identical to Study 1A] Notes: * Emissions refers to carbon dioxide, methane, and nitrous oxide. * Emissions rate assumes 1.24 lb CO2-equivalent per kilowatt hour and an average of 7% electricity transmission loss.</p>
<p><em>Page 4: Food GHG Emissions</em> Using a 100-watt incandescent light bulb for one hour emits 100 units of greenhouse gas emissions. Using this scale, how many units of greenhouse gas emissions do you think each of the following foods emits to produce and transport? [Instructions similar to Study 1A, asking for GHG units] [List of 19 foods, identical to Study 1A] Notes: * Foods are listed in terms of standard serving sizes. * Emissions refers to carbon dioxide, methane, and nitrous oxide. * Emissions includes production and transport from US manufacturer to distributor only and is based on an average distance of 1,500 miles travelled by a semi-trailer truck. * Emissions from further processing, transport between distributor and retailer, consumption, and disposal are not included.</p>
<p><em>Page 5: Attention Check Questions</em> How many miles do you assume food is transported on average between manufacturer (e.g., farm) and distributor? ____ According to the information on the previous page, how many units of greenhouse gas emissions are emitted by using a 100-watt incandescent light bulb for one hour? * 100 units * 500 units * 120 units * 80 units</p>
<p><em>Pages 6, 7, 8: Environmental Worldview, Demographics, Conclusion</em> [Identical to Study 1A]</p>
<hr>
</section>
<section id="supplementary-note-2-studies-1c-and-1d---sensitivity-of-results-to-reference-unit" class="level3">
<h3 class="anchored" data-anchor-id="supplementary-note-2-studies-1c-and-1d---sensitivity-of-results-to-reference-unit">Supplementary Note 2: Studies 1C and 1D - Sensitivity of Results to Reference Unit</h3>
<p>To examine the sensitivity of our findings to the reference unit used, we replicated Study 1A and 1B with a different sample and food reference unit. We randomly allocated 1,009 participants recruited from Amazon’s Mechanical Turk to either Study 1C (estimating energy consumption) or Study 1D (estimating GHG emissions). The studies were available only to people in the United States. The materials and procedure were nearly identical to Study 1A and 1B except that the reference unit provided for energy consumption and GHG emissions was in terms of both a “medium-sized tomato” as well as the use of “a 100-watt incandescent light bulb for one hour”. Both items were said to consume 100 units of energy (in Study 1C) or emit 100 units of GHG emissions (in Study 1D).</p>
<p>The 507 participants allocated to Study 1C ranged in age from 18 to 75 years with a mean of 33.5 (SD = 10.4). Among the survey respondents, 58% were female and 70% were employed full-time or part-time. Racially, 74% were non-Hispanic White, 6% Hispanic, 8% African American, and 10% Asian. Politically, 39% identified as Democrats, 38% as Independent, and 18% as Republican.</p>
<p>The 505 participants allocated to Study 1D ranged in age from 19 to 80 years with a mean of 34.5 (SD = 11.6). Among the survey respondents, 55% were female and 70% were employed full-time or part-time. Racially, 75% were non-Hispanic White, 5% Hispanic, 9% African American, and 9% Asian. Politically, 42% identified as Democrats, 32% as Independent, and 21% as Republican.</p>
<p>Figure S1 shows participants’ estimated energy used plotted against actual energy consumed after transforming both distributions with base-10 logarithms to reduce positive skew. Figure S2 shows participants’ estimated GHG emissions plotted against actual GHG emissions after transforming both distributions with base-10 logarithms to reduce positive skew. We ran the same mixed models as those reported in the main analysis. A summary of the models is provided in Table S1.</p>
<p>Compared to the main studies (that provided only an appliance reference unit), the replication studies (that provided both an appliance and a food reference unit) produced lines of best fit that were steeper and with less negative intercepts. Although the size of the difference between appliances and foods was reduced it remained statistically significant, thus supporting our main conclusion that consumers underestimate foods more than appliances.</p>
<p><em>Figure S1: Mean estimates of energy used relative to actual energy used. The red fitted line depicts the relationship between the actual energy consumed throughout the life-cycle of 18 foods (x-axis) and the estimates provided by Study 1A participants (y-axis). The blue fitted line depicts the actual energy used of 18 electrical appliances (x-axis) and the estimates provided by Study 1A participants (y-axis). Accurate estimates would produce a set of points that fall along the grey 45-degree line. As shown, participants underestimated the energy consumption of all foods and almost all appliances (with the exception of CFL light bulbs, laptop computers, and DVD players). The underestimation was greater for foods than for appliances. Note that all estimates are expressed in terms of “Energy Units” and participants were told that producing and transporting a medium-sized tomato uses 100 Energy Units. All data are logged. Error bars represent the standard error of the mean.</em></p>
<p><em>Figure S2: Mean estimates of GHG emitted relative to actual GHG emitted. The red fitted line depicts the relationship between the actual GHG emitted throughout the life-cycle of 18 foods (x-axis) and the estimates provided by Study 1B participants (y-axis). The blue fitted line depicts the actual GHG emitted of 18 electrical appliances (x-axis) and the estimates provided by Study 1B participants (y-axis). Accurate estimates would produce a set of points that fall along the grey 45-degree line. As shown, participants underestimated the GHG emitted of all foods and almost all appliances (with the exception of CFL light bulbs, laptop computers, and DVD players). The underestimation was greater for foods than for appliances. Note that all estimates are expressed in terms of “Greenhouse Gas Units” and participants were told that producing and transporting a medium-sized tomato emits 100 Greenhouse Gas Units. All data are logged. Error bars represent the standard error of the mean.</em></p>
<p><strong>Table S1.</strong> Results of multilevel regressions for predicting consumers’ perceptions of energy consumption (Study 1C) and greenhouse gas (GHG) emissions (Study 1D)</p>
<table class="caption-top table">
<colgroup>
<col style="width: 19%">
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 18%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Study 1C: Energy Consumption</th>
<th>Study 1C: Energy Consumption</th>
<th>Study 1D: GHG Emissions</th>
<th>Study 1D: GHG Emissions</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>Eq. S1</td>
<td>Eq. S2</td>
<td>Eq. S3</td>
<td>Eq. S4</td>
</tr>
<tr class="even">
<td>Intercept</td>
<td>-0.355***</td>
<td>-0.333***</td>
<td>-0.352***</td>
<td>-0.334***</td>
</tr>
<tr class="odd">
<td>Domain (domain)</td>
<td>-0.325***</td>
<td>-0.381***</td>
<td>-0.296***</td>
<td>-0.340***</td>
</tr>
<tr class="even">
<td>Log of actual value (actual)</td>
<td>0.279***</td>
<td>0.236***</td>
<td>0.241***</td>
<td>0.233***</td>
</tr>
<tr class="odd">
<td>Quadratic term (actual²)</td>
<td>0.025**</td>
<td>-0.029**</td>
<td>0.010</td>
<td>-0.031**</td>
</tr>
<tr class="even">
<td>domain*actual</td>
<td></td>
<td>0.107***</td>
<td></td>
<td>-0.007</td>
</tr>
<tr class="odd">
<td>domain*actual²</td>
<td></td>
<td>0.330***</td>
<td></td>
<td>0.136**</td>
</tr>
</tbody>
</table>
<p><em>Note: The independent variable domain refers to whether participants were estimating foods (coded “1”) or appliances (coded “0”). The independent variable actual, which was logged and mean-centered, refers to the actual energy consumed or GHG emissions for each item. The dependent variable - estimated, which was also logged and centered relative to the mean of actual – refers to the participant’s estimated energy consumed or GHG emissions for each item. Coefficients are unstandardized. ***p &lt; 0.001, **p &lt; 0.01, *p &lt; 0.05.</em></p>
<p>It is worth discussing one aspect of our study that may also have affected the participant’s responses. Like previous research, we selected the energy consumed by a 100W light-bulb during one hour as a reference unit, which represents a relatively low energy consumption relative to the energy use of the items being evaluated. This low reference point is likely to have reduced overall estimates because people often make judgments that are too close to the reference point. Although the reference unit may tend to shift all estimates in aggregate, our primary focus was on the relative underestimation of food versus appliances. This inter-domain comparison is not influenced by the specific choice of reference unit. However, a potentially interesting future direction may be to examine between-domain behavior change preferences (e.g., willingness to eat less meat versus use less air conditioning).</p>
<hr>
</section>
<section id="supplementary-note-3-actual-life-cycle-energy-use-and-ghg-emissions-for-different-types-of-food-and-appliances" class="level3">
<h3 class="anchored" data-anchor-id="supplementary-note-3-actual-life-cycle-energy-use-and-ghg-emissions-for-different-types-of-food-and-appliances">Supplementary Note 3: Actual Life-Cycle Energy Use and GHG Emissions for Different Types of Food and Appliances</h3>
<p>The data sources for actual appliance energy use are shown in Table S2. The data reflect the best available information at the time of analysis. Because energy consumption of different appliances depends on its technical specifications, mode of use (e.g., a freezer will consume more electricity if doors are opened frequently), and environmental conditions (e.g., a freezer consumes more electricity if placed in a warmer room), no single estimate of power consumption is correct. In fact, several studies report ranges. However, to assess the accuracy of consumer’s perceptions of energy consumption it is necessary to have a best estimate. To get such a value, when a range was given in a source, we used the middle value. When multiple values were available from different sources, we used the arithmetic mean. We then used the arithmetic mean of all sources to produce an “actual” value.</p>
<p>The GHG emissions associated with energy consumption vary depending on the energy mix used in the power grid from which electricity is drawn, and the magnitude of energy losses in the power transmission and distribution. To obtain a best point-estimate of GHG emissions, we used the best-estimates of energy use and assumed: (a) electric power transmission resulted in a 7% loss of electricity, (b) 1.24 pounds of greenhouse gases were emitted per kWh consumed, and c) methane had 25 times the global warming potential of carbon dioxide while nitrous oxide’s warming potential was 298 times that of carbon dioxide.</p>
<p>Because it was possible that consumers would provide an estimate of energy use and GHG emissions that deviated from our “actual” value but was nevertheless within the range of values estimated from our sources, we performed a sensitivity analysis on these values (see Supplementary Note 4).</p>
<p><strong>Table S2.</strong> Data sources and actual values for energy consumed and GHG emissions released for using various appliances for one hour</p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 37%">
<col style="width: 12%">
<col style="width: 22%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>Appliance</th>
<th>Energy Consumed (W/hr) - Sources (AltE, SVP, CWLP, EV, AS)</th>
<th>Mean Energy (W/hr)</th>
<th>GHG Emissions (lb CO2 equiv / hr)</th>
<th>Energy/GHG Units*</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Incandescent light bulb</td>
<td>100, 100, 100, -, -</td>
<td>100</td>
<td>0.13</td>
<td>100</td>
</tr>
<tr class="even">
<td>CFL light bulb</td>
<td>23, 27, 25, 22, -</td>
<td>24</td>
<td>0.03</td>
<td>24</td>
</tr>
<tr class="odd">
<td>Desktop computer</td>
<td>80-200, 60-250, 90, -, 200</td>
<td>146</td>
<td>0.19</td>
<td>146</td>
</tr>
<tr class="even">
<td>Laptop computer</td>
<td>20-75, 20-50, -, -, -</td>
<td>41</td>
<td>0.05</td>
<td>41</td>
</tr>
<tr class="odd">
<td>Electric clothes dryer</td>
<td>4000, 2500-4000, 2700, 3125, 5000</td>
<td>3615</td>
<td>4.79</td>
<td>3615</td>
</tr>
<tr class="even">
<td>Handheld clothes iron</td>
<td>1000, 1080, -, -, 1000</td>
<td>1027</td>
<td>1.36</td>
<td>1027</td>
</tr>
<tr class="odd">
<td>Washing machine</td>
<td>500, -, 250, 281, 500</td>
<td>383</td>
<td>0.51</td>
<td>383</td>
</tr>
<tr class="even">
<td>Portable electric heater</td>
<td>1500, 1500, 1500, 1500, 1200</td>
<td>1440</td>
<td>1.91</td>
<td>1440</td>
</tr>
<tr class="odd">
<td>Room air-conditioner</td>
<td>1000, 730-1800, -, 900, 750-1050</td>
<td>1016</td>
<td>1.35</td>
<td>1016</td>
</tr>
<tr class="even">
<td>Central air-conditioner</td>
<td>2000-5000, 3000, 850-6000, 3000, 3500</td>
<td>3285</td>
<td>4.35</td>
<td>3285</td>
</tr>
<tr class="odd">
<td>Coffee maker</td>
<td>800, 400, -, -, 900</td>
<td>700</td>
<td>0.93</td>
<td>700</td>
</tr>
<tr class="even">
<td>Dishwasher</td>
<td>1200-1500, 1000-2170, 1000, 500-800, 1300</td>
<td>1177</td>
<td>1.56</td>
<td>1177</td>
</tr>
<tr class="odd">
<td>Freezer</td>
<td>445, 125, 188, 49-166, 335</td>
<td>240</td>
<td>0.32</td>
<td>240</td>
</tr>
<tr class="even">
<td>Refrigerator</td>
<td>475, 77-333, 140-373, 44-188, 300-500</td>
<td>291</td>
<td>0.38</td>
<td>291</td>
</tr>
<tr class="odd">
<td>Toaster oven</td>
<td>800-1500, 750, -, -, 1150</td>
<td>1017</td>
<td>1.35</td>
<td>1017</td>
</tr>
<tr class="even">
<td>Microwave oven</td>
<td>600-1500, 1440, 750, 889, 1300</td>
<td>1086</td>
<td>1.44</td>
<td>1086</td>
</tr>
<tr class="odd">
<td>Television</td>
<td>-, 12-480, 300, -, 180</td>
<td>242</td>
<td>0.32</td>
<td>242</td>
</tr>
<tr class="even">
<td>Vacuum cleaner</td>
<td>200-700, 750, -, -, 800</td>
<td>667</td>
<td>0.88</td>
<td>667</td>
</tr>
<tr class="odd">
<td>DVD player</td>
<td>-, 30, -, 33, -</td>
<td>32</td>
<td>0.04</td>
<td>32</td>
</tr>
</tbody>
</table>
<p><em>* Described to participants as “Energy Units” and “GHG Emissions Units”</em> <em>(Source keys: AltE, SVP, CWLP, EV, AS correspond to references in the original supplementary material)</em></p>
<p>Energy usage and GHG emissions associated with food production, processing, and transportation, depend on a large number of factors and hence, point-estimates of these impacts for generic foods are imprecise. For example, energy use and GHG emissions of vegetables depend on crop type, soil characteristics, hydro climatic conditions, pest and nutrient management, the use of irrigation, number of miles traveled, type of transportation, and storage technology. Nevertheless, our study required a best estimate for each food to compare to consumer perceptions. Our best estimates on energy use and associated GHG emissions of different foods were based on data from the LCA Software &amp; Carbon Footprint Analyzer FoodCarbonScopeTM, produced by the company CleanMetricsTM http://cleanmetrics.net/foodcarbonscope. FoodCarbonScopeTM is a web-based software tool for conducting Environmental Life Cycle Assessments of food. It provides estimates of life-cycle GHG emissions, energy use, and water use in food and beverage products, and has the largest commercially available life cycle inventory database for North American food production and processing. In May 2016 we were granted temporary access to the tool, which allowed us to search for foods that had data from multiple American sources, from which we took the arithmetic mean as our “actual” value. We estimated the serving size and serving size weight. A summary of this analysis is provided in Tables S3 and S4. Note that all values include 1,500 miles of transport by a semi-trailer.</p>
<p>Because it is possible that consumers would provide an estimate of energy use and GHG emissions that deviated from our “actual” value but was nevertheless within the range of values estimated by different sources, we performed sensitivity analysis on these values (see Supplementary Note 4).</p>
<p><strong>Table S3.</strong> Data sources and actual values for energy consumed for producing and transporting various foods in Study 1.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 8%">
<col style="width: 20%">
<col style="width: 10%">
<col style="width: 31%">
<col style="width: 16%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>Food</th>
<th>Serving Size Description</th>
<th>Weight (lb)</th>
<th>Energy Consumed (MJ / kg) - Sources 1-4</th>
<th>Mean Energy (MJ/kg)</th>
<th>Energy Units</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Maize</td>
<td>Half a cup of maize</td>
<td>0.16</td>
<td>4.78, 4.09, 4.16, 5.33</td>
<td>4.6</td>
<td>93</td>
</tr>
<tr class="even">
<td>Soybeans</td>
<td>Half a cup of soybeans</td>
<td>0.28</td>
<td>5.14, 4.69, 5.00, 4.67</td>
<td>4.9</td>
<td>173</td>
</tr>
<tr class="odd">
<td>Barley</td>
<td>Half a cup of barley</td>
<td>0.22</td>
<td>5.67, 4.86, 6.04, 5.01</td>
<td>5.4</td>
<td>150</td>
</tr>
<tr class="even">
<td>Wheat</td>
<td>Half a cup of wheat</td>
<td>0.21</td>
<td>4.39, 6.10, 5.25, 5.89</td>
<td>5.4</td>
<td>144</td>
</tr>
<tr class="odd">
<td>Rice</td>
<td>Half a cup of rice</td>
<td>0.20</td>
<td>9.81, 6.23, 11.56, 10.83</td>
<td>9.6</td>
<td>247</td>
</tr>
<tr class="even">
<td>Beans</td>
<td>Half a cup of beans</td>
<td>0.20</td>
<td>9.04, 11.65, 10.70, 11.19</td>
<td>10.6</td>
<td>272</td>
</tr>
<tr class="odd">
<td>Walnuts</td>
<td>A handful of walnuts</td>
<td>0.14</td>
<td>12.42, 13.04, -, -</td>
<td>12.7</td>
<td>220</td>
</tr>
<tr class="even">
<td>Tomatoes</td>
<td>1 medium-sized tomato</td>
<td>0.27</td>
<td>3.72, 5.25, 5.14, 5.25</td>
<td>4.8</td>
<td>165</td>
</tr>
<tr class="odd">
<td>Oranges</td>
<td>1 medium-sized orange</td>
<td>0.31</td>
<td>3.45, 4.09, 4.11, -</td>
<td>3.9</td>
<td>151</td>
</tr>
<tr class="even">
<td>Apples</td>
<td>1 medium-sized apple</td>
<td>0.40</td>
<td>4.64, 6.86, 4.05, 5.36</td>
<td>5.2</td>
<td>264</td>
</tr>
<tr class="odd">
<td>Potatoes</td>
<td>1 medium-sized potato</td>
<td>0.47</td>
<td>7.02, 4.55, 6.71, 8.74</td>
<td>6.8</td>
<td>399</td>
</tr>
<tr class="even">
<td>Eggs</td>
<td>2 large eggs</td>
<td>0.22</td>
<td>19.51, 17.60, -, -</td>
<td>18.6</td>
<td>516</td>
</tr>
<tr class="odd">
<td>Almonds</td>
<td>A handful of almonds</td>
<td>0.16</td>
<td>23.76, 33.63, 34.18, 47.89</td>
<td>34.9</td>
<td>692</td>
</tr>
<tr class="even">
<td>Tofu</td>
<td>1 tofu steak</td>
<td>0.38</td>
<td>9.14, 8.86, -, -</td>
<td>9.0</td>
<td>425</td>
</tr>
<tr class="odd">
<td>Milk</td>
<td>1 cup of milk</td>
<td>0.54</td>
<td>5.82, 6.57, 6.17, 8.36</td>
<td>6.7</td>
<td>456</td>
</tr>
<tr class="even">
<td>Cheese</td>
<td>2 slices of cheese</td>
<td>0.12</td>
<td>43.25, 43.01, -, -</td>
<td>43.1</td>
<td>672</td>
</tr>
<tr class="odd">
<td>Pork</td>
<td>A small fist of pork</td>
<td>0.22</td>
<td>29.46, 27.57, 33.21, 37.06</td>
<td>31.8</td>
<td>884</td>
</tr>
<tr class="even">
<td>Beef</td>
<td>A small fist of beef</td>
<td>0.22</td>
<td>37.03, 50.22, 79.42, -</td>
<td>55.6</td>
<td>1544</td>
</tr>
<tr class="odd">
<td>Lamb</td>
<td>A small fist of lamb</td>
<td>0.22</td>
<td>70.29, 64.89, 70.32, -</td>
<td>68.5</td>
<td>1904</td>
</tr>
</tbody>
</table>
<p><strong>Table S4.</strong> Data sources and actual values for GHG emissions released in producing and transporting various foods in Study 1.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 6%">
<col style="width: 16%">
<col style="width: 8%">
<col style="width: 32%">
<col style="width: 14%">
<col style="width: 10%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>Food</th>
<th>Serving Size Description</th>
<th>Weight (lb)</th>
<th>GHG Emissions (kg CO2 equiv. / kg) - Sources 1-4</th>
<th>Mean GHG (kg CO2e/kg)</th>
<th>lb CO2e / serv.</th>
<th>GHG Emission Units</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Maize</td>
<td>Half a cup of maize</td>
<td>0.16</td>
<td>0.52, 0.43, 0.41, 0.61</td>
<td>0.49</td>
<td>0.08</td>
<td>59</td>
</tr>
<tr class="even">
<td>Soybeans</td>
<td>Half a cup of soybeans</td>
<td>0.28</td>
<td>0.78, 0.75, 0.77, 0.64</td>
<td>0.74</td>
<td>0.21</td>
<td>156</td>
</tr>
<tr class="odd">
<td>Barley</td>
<td>Half a cup of barley</td>
<td>0.22</td>
<td>0.50, 0.48, 0.53, 0.46</td>
<td>0.49</td>
<td>0.11</td>
<td>82</td>
</tr>
<tr class="even">
<td>Wheat</td>
<td>Half a cup of wheat</td>
<td>0.21</td>
<td>0.50, 0.59, 0.53, 0.53</td>
<td>0.54</td>
<td>0.11</td>
<td>86</td>
</tr>
<tr class="odd">
<td>Rice</td>
<td>Half a cup of rice</td>
<td>0.20</td>
<td>2.25, 1.71, 2.53, 2.34</td>
<td>2.21</td>
<td>0.45</td>
<td>339</td>
</tr>
<tr class="even">
<td>Beans</td>
<td>Half a cup of beans</td>
<td>0.20</td>
<td>1.00, 0.98, 0.93, 1.21</td>
<td>1.03</td>
<td>0.21</td>
<td>158</td>
</tr>
<tr class="odd">
<td>Walnuts</td>
<td>A handful of walnuts</td>
<td>0.14</td>
<td>0.94, 1.09, -, -</td>
<td>1.02</td>
<td>0.14</td>
<td>105</td>
</tr>
<tr class="even">
<td>Tomatoes</td>
<td>1 medium-sized tomato</td>
<td>0.27</td>
<td>0.30, 0.42, 0.52, 0.42</td>
<td>0.42</td>
<td>0.11</td>
<td>85</td>
</tr>
<tr class="odd">
<td>Oranges</td>
<td>1 medium-sized orange</td>
<td>0.31</td>
<td>0.28, 0.30, 0.31, -</td>
<td>0.30</td>
<td>0.09</td>
<td>69</td>
</tr>
<tr class="even">
<td>Apples</td>
<td>1 medium-sized apple</td>
<td>0.40</td>
<td>0.34, 0.46, 0.29, 0.37</td>
<td>0.37</td>
<td>0.15</td>
<td>110</td>
</tr>
<tr class="odd">
<td>Potatoes</td>
<td>1 medium-sized potato</td>
<td>0.47</td>
<td>0.51, 0.37, 0.51, 0.64</td>
<td>0.51</td>
<td>0.24</td>
<td>179</td>
</tr>
<tr class="even">
<td>Eggs</td>
<td>2 large eggs</td>
<td>0.22</td>
<td>2.04, 2.07, -, -</td>
<td>2.06</td>
<td>0.45</td>
<td>341</td>
</tr>
<tr class="odd">
<td>Almonds</td>
<td>A handful of almonds</td>
<td>0.16</td>
<td>2.07, 2.63, 2.65, 3.75</td>
<td>2.78</td>
<td>0.44</td>
<td>329</td>
</tr>
<tr class="even">
<td>Tofu</td>
<td>1 tofu steak</td>
<td>0.38</td>
<td>0.89, 0.87, -, -</td>
<td>0.88</td>
<td>0.33</td>
<td>248</td>
</tr>
<tr class="odd">
<td>Milk</td>
<td>1 cup of milk</td>
<td>0.54</td>
<td>1.20, 1.28, 1.34, 1.90</td>
<td>1.43</td>
<td>0.77</td>
<td>579</td>
</tr>
<tr class="even">
<td>Cheese</td>
<td>2 slices of cheese</td>
<td>0.12</td>
<td>10.02, 10.00, -, -</td>
<td>10.01</td>
<td>1.24</td>
<td>933</td>
</tr>
<tr class="odd">
<td>Pork</td>
<td>A small fist of pork</td>
<td>0.22</td>
<td>4.80, 4.46, 5.14, 5.79</td>
<td>5.05</td>
<td>1.11</td>
<td>838</td>
</tr>
<tr class="even">
<td>Beef</td>
<td>A small fist of beef</td>
<td>0.22</td>
<td>12.94, 14.57, 17.31, -</td>
<td>14.94</td>
<td>3.29</td>
<td>2481</td>
</tr>
<tr class="odd">
<td>Lamb</td>
<td>A small fist of lamb</td>
<td>0.22</td>
<td>20.66, 18.63, 24.61, -</td>
<td>21.30</td>
<td>4.69</td>
<td>3538</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="supplementary-note-4-studies-1a-and-1b---testing-additional-covariates-and-sensitivity-of-results-to-assumed-actual-values" class="level3">
<h3 class="anchored" data-anchor-id="supplementary-note-4-studies-1a-and-1b---testing-additional-covariates-and-sensitivity-of-results-to-assumed-actual-values">Supplementary Note 4: Studies 1A and 1B - Testing Additional Covariates and Sensitivity of Results to Assumed Actual Values</h3>
<p>A within-subjects t-test revealed that the mean individual-level correlation between perceived and actual values was significantly low for foods than for appliances for energy use (Mappliances = .31, SD = .27, vs.&nbsp;Mfood = .24, SD = .25), t(517) = 4.77, p &lt; .0001, and GHG emissions (Mappliances = .28, SD = .28, vs.&nbsp;Mfood= .24, SD = .28), t(513) = 2.18, p = .03. We note that the food items used in our study had a more restricted range of “actual” values (e.g., lowest energy = 93 energy units; highest energy = 1904 energy units) compared to appliances (lowest energy = 32 energy units; highest energy = 3,615 energy units), which can reduce correlations.</p>
<p>In order to examine the effect of covariates in Study 1A and 1B, we ran the same mixed-effect models as described in the main text a second time, now including all of the demographic variables (i.e., Gender [“Male” reference level], Age, Ethnicity [“Other” reference level], Education, Employment [“Homemaker” reference level], Income, Political Orientation – Economic Issues, Political Orientation – Social Issues, Political Party [“Other” reference level], NEPr (i.e., environmental worldview), and Order as covariates. A summary of the models is provided in Table S5.</p>
<p>In Study 1A, in addition to the effects described in the main analysis, there was a significant effect of NEPr indicating that estimates were higher for those who had a more pro-environmental worldview. This observation is consistent with prior research.</p>
<p>In Study 1B, in addition to the effects described in the main analysis, there was a significant effect of NEPr again indicating that estimates were higher for those who had a more pro-environmental worldview. There was a significant effect of gender indicating that estimates were higher for those who were female. This observation is consistent with some prior research (but not all). There was a significant effect of education indicating that estimates were higher for those who were more educated. There was a significant effect of income indicating that estimates were higher for those who reported a higher family income bracket.</p>
<p><strong>Table S5.</strong> Results of multilevel regressions for predicting consumers’ perceptions of energy consumption (Study 1B) and greenhouse gas (GHG) emissions (Study 1B) including covariates.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 43%">
<col style="width: 30%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Predictor Variable</th>
<th>Study 1A: Energy Consumption</th>
<th>Study 1B: GHG Emissions</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>-0.952*</td>
<td>-1.149***</td>
</tr>
<tr class="even">
<td>Domain (domain)</td>
<td>-0.530***</td>
<td>-0.509***</td>
</tr>
<tr class="odd">
<td>Log of actual value (actual)</td>
<td>0.210***</td>
<td>0.176***</td>
</tr>
<tr class="even">
<td>Quadratic term (actual²)</td>
<td>0.025*</td>
<td>0.010</td>
</tr>
<tr class="odd">
<td>domain*actual</td>
<td>-0.033*</td>
<td>-0.062***</td>
</tr>
<tr class="even">
<td>domain* actual²</td>
<td>0.421***</td>
<td>0.132***</td>
</tr>
<tr class="odd">
<td>Gender</td>
<td>0.029</td>
<td>-0.131*</td>
</tr>
<tr class="even">
<td>Age</td>
<td>-0.005</td>
<td>-0.002</td>
</tr>
<tr class="odd">
<td>Ethnicity [White]</td>
<td>-0.047</td>
<td>-0.085</td>
</tr>
<tr class="even">
<td>Ethnicity [African American]</td>
<td>-0.172</td>
<td>-0.025</td>
</tr>
<tr class="odd">
<td>Ethnicity [Asian]</td>
<td>0.169</td>
<td>-0.098</td>
</tr>
<tr class="even">
<td>Ethnicity [Hispanic]</td>
<td>0.011</td>
<td>-0.087</td>
</tr>
<tr class="odd">
<td>Education</td>
<td>0.012</td>
<td>0.043*</td>
</tr>
<tr class="even">
<td>Employment [Employed full time]</td>
<td>0.028</td>
<td>-0.110</td>
</tr>
<tr class="odd">
<td>Employment [Employed part time]</td>
<td>0.127</td>
<td>-0.064</td>
</tr>
<tr class="even">
<td>Employment [Not employed but looking]</td>
<td>-0.092</td>
<td>0.018</td>
</tr>
<tr class="odd">
<td>Employment [Not employed and not looking]</td>
<td>0.062</td>
<td>0.009</td>
</tr>
<tr class="even">
<td>Employment [Retired]</td>
<td>0.006</td>
<td>0.033</td>
</tr>
<tr class="odd">
<td>Employment [Student]</td>
<td>0.080</td>
<td>0.030</td>
</tr>
<tr class="even">
<td>Income</td>
<td>0.009</td>
<td>0.039*</td>
</tr>
<tr class="odd">
<td>Political Orientation – Economic Issues</td>
<td>0.029</td>
<td>0.011</td>
</tr>
<tr class="even">
<td>Political Orientation – Social Issues</td>
<td>-0.041</td>
<td>-0.010</td>
</tr>
<tr class="odd">
<td>Political Party [Democrat]</td>
<td>-0.020</td>
<td>-0.193</td>
</tr>
<tr class="even">
<td>Political Party [Independent]</td>
<td>-0.034</td>
<td>-0.121</td>
</tr>
<tr class="odd">
<td>Political Party [Republican]</td>
<td>-0.142</td>
<td>-0.069</td>
</tr>
<tr class="even">
<td>NEPr</td>
<td>0.008*</td>
<td>0.010**</td>
</tr>
<tr class="odd">
<td>Order</td>
<td>0.031</td>
<td>-0.106*</td>
</tr>
</tbody>
</table>
<p><em>Note: Coefficients are unstandardized. ***p &lt;0.001, **p &lt; 0.01, *p &lt; 0.05.</em></p>
<p>To examine the sensitivity of our findings to the <em>actual</em> values, we re-ran all analyses reported in the main text for Study 1A and 1B assuming energy consumption and GHG emissions of food and appliances was equal to the minimum rather than the average of the values reported by the different sources.</p>
<p>Figure S3 shows participants’ estimated energy used plotted against conservative actual energy consumed after transforming both distributions with base-10 logarithms to reduce positive skew. Figure S4 shows participants’ estimated GHG emissions plotted against conservative actual GHG emissions after transforming both distributions with base-10 logarithms to reduce positive skew. We ran the same mixed models as those reported in the main analysis. A summary of the models is provided in Table S6.</p>
<p>Compared to the main analysis, the conservative analysis produced lines of best fit that were shallower and with less negative intercepts. Importantly, the size of the difference between appliances and foods was very similar between analyses, supporting our main conclusion that consumers underestimate foods more than appliances.</p>
<p><em>Figure S3: Mean estimates of energy used relative to conservative actual energy used. The red fitted line depicts the relationship between the conservative actual energy consumed throughout the life-cycle of 19 foods (x-axis) and the estimates provided by Study 1A participants (y-axis). The blue fitted line depicts the conservative actual energy used of 18 electrical appliances (x-axis) and the estimates provided by Study 1A participants (y-axis)…</em></p>
<p><em>Figure S4: Mean estimates of GHG emitted relative to conservative actual GHG emitted. The red fitted line depicts the relationship between the conservative actual GHG emitted throughout the life-cycle of 19 foods (x-axis) and the estimates provided by Study 1B participants (y-axis). The blue fitted line depicts the conservative actual GHG emitted of 18 electrical appliances (x-axis) and the estimates provided by Study 1B participants (y-axis)…</em></p>
<p><strong>Table S6.</strong> Results of multilevel regressions for predicting consumers’ perceptions of energy consumption (Study 1A) and greenhouse gas (GHG) emissions (Study 1B) relative to conservative actual values</p>
<table class="caption-top table">
<colgroup>
<col style="width: 19%">
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 18%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Study 1A: Energy Consumption</th>
<th>Study 1A: Energy Consumption</th>
<th>Study 1B: GHG Emissions</th>
<th>Study 1B: GHG Emissions</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>Eq. S1</td>
<td>Eq. S2</td>
<td>Eq. S3</td>
<td>Eq. S4</td>
</tr>
<tr class="even">
<td>Intercept</td>
<td>-0.512***</td>
<td>-0.486***</td>
<td>-0.492***</td>
<td>-0.504***</td>
</tr>
<tr class="odd">
<td>Domain (domain)</td>
<td>-0.484***</td>
<td>-0.546***</td>
<td>-0.509***</td>
<td>-0.484***</td>
</tr>
<tr class="even">
<td>Log of actual value (actual)</td>
<td>0.153***</td>
<td>0.130***</td>
<td>0.086***</td>
<td>0.094***</td>
</tr>
<tr class="odd">
<td>Quadratic term (actual²)</td>
<td>0.120***</td>
<td>0.066***</td>
<td>0.015***</td>
<td>0.039***</td>
</tr>
<tr class="even">
<td>domain*actual</td>
<td></td>
<td>-0.086***</td>
<td></td>
<td>0.006</td>
</tr>
<tr class="odd">
<td>domain*actual²</td>
<td></td>
<td>0.404***</td>
<td></td>
<td>-0.074**</td>
</tr>
</tbody>
</table>
<p><em>Note: Coefficients are unstandardized. ***p &lt; 0.001, **p &lt; 0.01, *p &lt; 0.05.</em></p>
<hr>
</section>
<section id="supplementary-note-5-study-2-stimuli" class="level3">
<h3 class="anchored" data-anchor-id="supplementary-note-5-study-2-stimuli">Supplementary Note 5: Study 2 Stimuli</h3>
<p><em>Demographics [These questions were asked prior to the bundle of studies being carried out]</em> [Standard demographic questions: Age, Gender, Ethnicity/Race, Student Status, Employment Status, Political Views, Education Level, Household Income, Religious Affiliation, English Proficiency, Time in US - omitted here for brevity]</p>
<p><em>Page 1: Instructions</em> For completing this particular study, you will earn $6. However, $3 of this payment must be spent during this study to purchase goods of your choosing. You will actually get these goods (in addition to your cash payment) at the end of the study.</p>
<p><em>Page 2: Choice</em> In this study, you will be buying soup and the following options are available to you. Note that there are 6 options and they are arranged in two rows. At the end of the study, you will actually receive the cans of soup you buy.</p>
<p>[Table showing 6 soup options: 3 Beef (Beef Noodle, Beef w/ Veg &amp; Barley, Vegetable Beef), 3 Vegetable (Vegetarian Vegetable, Old Fashioned Vegetable, Minestrone). Each shows:] * Product (Name &amp; Photo) * Price ($1.00) * Serving Size (0.5 cup) * Calories * Fats / serving * Carbohydrates / serving * Proteins / serving * Carbon Footprint* / serving (showing g CO2e and equivalent light bulb minutes in a light bulb graphic) * Carbon Footprint Rating^ / serving (showing a green-to-red scale with a triangle indicating the product’s relative footprint)</p>
<p><em>(Example values from Fig 3 / text for Vegetable Beef Soup: 90 Cal, 1g Fat, 15g Carb, 4g Protein, 1,281g CO2e, 2,127 light bulb minutes)</em> <em>(Example values from text for Vegetarian Vegetable Soup: 90 Cal, 0.5g Fat, 18g Carb, 3g Protein, 208g CO2e, 345 light bulb minutes)</em></p>
<p><em>* The “Carbon Footprint” indicates the total amount of greenhouse gases or their equivalent that were released in order to produce a serving of this food… translated into the number of minutes a 100-watt light bulb would have to be illuminated…</em> <em>^ The “Carbon Footprint Rating” provides a visual representation of the carbon footprint of this product compared to other products in the same category…</em></p>
<p>Which THREE soups will you buy? [List of 6 soups] Please briefly explain why you chose these three soups _________________</p>
<p><em>Page 3: Food GHG Emissions</em> Using a 100-watt incandescent light bulb for one hour emits 100 units of greenhouse gas emissions. Using this scale, how many units of greenhouse gas emissions do you think each of the following foods emits to produce and transport? [Instructions similar to Study 1B] * Units of emissions for: Beef soup (half a cup) * Units of emissions for: Vegetable soup (half a cup) Notes: [Identical to Study 1B Food GHG Notes]</p>
<p><em>Page 4: Attention Check Questions</em> With the following questions, we are interested to know how much you remember from the food choice task that you just completed. Which product were you NOT presented with earlier? * Bean with Bacon Soup * Minestrone Soup * Vegetarian Vegetable Soup * Beef Noodle Soup How many soups were you presented with? * 5 * 6 * 7 * 8 * 9 * 10 Were you provided with carbon footprint information for each soup? * No * Yes</p>
<p><em>Page 5: Familiarity</em> How familiar are you with the soups presented in this study? [Possible responses: “I have never seen this soup before”; “I have seen this soup before but never tasted it”; “I have tasted this soup before”] [List of 6 soups]</p>
<p><em>Page 6: Environmental Worldview</em> [NEPr Scale questions - omitted here for brevity]</p>
<p><em>Pages 7: Food Choice Questionnaire</em> It is important to me that the food I eat on a typical day… [all items answered on a 5-point response scale from 1 = “Strongly agree to 5 = “Strongly disagree; subscale has been identified in brackets after each item] [FCQ Items listed covering Health, Mood, Convenience, Sensory appeal, Natural content, Price, Weight control, Familiarity, Animal Welfare, Environmental protection, Political values, Religion - omitted here for brevity]</p>
<p><em>Page 8: Demographics</em> [Additional Demographics: Diet type (Vegan, Vegetarian, etc.), Dieting Status, Political Affiliation - omitted here for brevity]</p>
<p><em>Page 9: Conclusion</em> Thanks for participating in our study… We will use your responses to help us understand how we can help people make more accurate estimations… Thank you for your participation in this research. If you have any reactions, comments, suggestions… please provide them below. We really do value your feedback! ____</p>
<hr>
</section>
<section id="supplementary-note-6-study-2---additional-analyses" class="level3">
<h3 class="anchored" data-anchor-id="supplementary-note-6-study-2---additional-analyses">Supplementary Note 6: Study 2 - Additional Analyses</h3>
<p>We conducted a regression analysis with group, NEPr, scores from the subscales of the Food Choice Questionnaire (FCQ; health, mood, convenience, sensory appeal, natural content, price, weight control, familiarity, animal welfare, environmental protection, political values, religion [each coded “1” for Strongly Disagree up to “5” for Strongly Agree), and the demographics variables (gender [coded “1” for Man and “2” for Woman], age, race [coded “1” for Caucasian/white, “2” for “African American/black”, 3 for Asian/pacific islander, “4” for Hispanic/Latino, “5” for Native American, and “6” for Other], employment status [coded “1” for Employed full time, etc.], education status [coded “1” for Some high school up to “6” for Graduate], political party [coded “1” for Democrat, etc.], household income [coded “0” for $0-9,999 up to “7” for $120,000+], and dietary status [coded “0” for eats red meat and “1” for avoids red meat]) entered as predictor variables, and the average number of beef soups purchased as the outcome variable.</p>
<p>The analysis revealed a significant effect of group, B = -.49, t(97) = -2.93, p = .004, a significant effect of diet type, B = -1.14, t(97) = -5.038, p &lt; .0001, a significant effect for the political values FCQ subscale, B = -.31, t(97) = -2.181, p = .03, a significant effect for the religion FCQ subscale, B = .25, t(97) = 3.01, p = .03, a significant effect for the environmental protection FCQ subscale, B = .34, t(97) = -2.18, p = .03, and a significant effect of education, B = -.153, t(97) = -2.21, p = .03. In sum, those less likely to purchase cans of beef soup were presented with the GHG emissions information, more educated, have a diet that excluded red meat, and self-reported to choose foods that were aligned with their religious, political, and environmental protection values.</p>
<p>We conducted another regression analysis with the same variables entered as predictor variables, and beef-to-vegetable soup GHG emissions ratio purchased as the outcome variable. This analysis once again excluded to two outliers who produced ratios more than six standard deviations from the mean. The analysis revealed a significant effect of group, B = 1.30, t(95) = 3.14, p = .002. No other variables were significant predictors. In sum, those who tended to estimate a higher ratio were presented with the GHG emissions information.</p>
<hr>
</section>
<section id="supplementary-note-7-actual-life-cycle-ghg-emissions-for-a-range-of-prepared-soups" class="level3">
<h3 class="anchored" data-anchor-id="supplementary-note-7-actual-life-cycle-ghg-emissions-for-a-range-of-prepared-soups">Supplementary Note 7: Actual Life-Cycle GHG Emissions for a Range of Prepared Soups</h3>
<p>For Study 2, the actual values of GHG emissions from the life-cycle of different types of vegetable and beef soup were based on data from the website www.eatlowcarbon.org/food-scores, which was last accessed 23 November 2017. According to this website: &gt; EatLowCarbon.org was created by Bon Appétit Management Company, a food service pioneer operating hundreds of cafés all over America for corporations, universities, and specialty venues. Bon Appétit is known for tackling pressing social issues such as local food, animal welfare, antibiotics in animal agriculture, farmworker rights, and more. Bon Appétit worked with the nonprofit environmental group Ecotrust to compile and conduct peer-reviewed Life Cycle Assessments from which the information on this site is drawn. Researchers use LCA to calculate the environmental impact of a product’s entire life cycle: for food items, that includes the inputs, such as fertilizer, that went into growing it, and the energy that went into transporting, processing and cooking it.</p>
<p>According to an email correspondence with Bon Appétit: &gt; We hired the organization EcoTrust to compile peer reviewed Life Cycle Assessments for single-ingredient foods and combine them according to “recipes” for the dishes shown on the site. That includes the ingredients, how far they traveled (either “domestic” or “international”) and information about how they were cooked.</p>
<p>The EatLowCarbon.org website listed the following soups: * Beef Chili Soup – 1,281 grams of CO2e * Chicken Noodle Soup – 253 grams of CO2e * Minestrone Soup – 189 grams of CO2e * Vegetarian Chili – 86 grams of CO2e * Spinach and Pea Stew – 78 grams of CO2e * Three Bean Soup – 54 grams of CO2e * Lentil Soup - 54 grams of CO2e</p>
<p>In order to generate the values used in Study 2, we took the value for Beef Chili Soup (1,281 g CO2e) and added/subtracted 10% of it (i.e., 128) to create two new values: 1,153 and 1,409. We then allocated these three values to the three beef soups used in the study: * Beef Noodle Soup – 1,409 grams of CO2e * Beef with Vegetables and Barley Soup – 1,153 grams of CO2e * Vegetable Beef Soup – 1,281 grams of CO2e</p>
<p>Similarly, we took the value for Minestrone Soup (189 g CO2e) and added/subtracted 10% of it (i.e., 19) to create two new values: 170 and 208. We then allocated these three values to the three vegetable soups used in the study: * Vegetarian Vegetable Soup – 208 grams of CO2e * Old Fashioned Vegetable Soup – 170 grams of CO2e * Minestrone Soup – 189 grams of CO2e</p>
</section>
<section id="references-supplementary-material" class="level3">
<h3 class="anchored" data-anchor-id="references-supplementary-material">References (Supplementary Material)</h3>
<ol type="1">
<li>Attari, S. Z., DeKay, M. L., Davidson, C. I. &amp; De Bruin, W. B. Public perceptions of energy consumption and savings. <em>Proceedings of the National Academy of Sciences</em> <strong>107</strong>, 16054-16059 (2010).</li>
<li>Epley, N. &amp; Gilovich, T. The anchoring-and-adjustment heuristic: Why the adjustments are insufficient. <em>Psychological Science</em> <strong>17</strong>, 311-318 (2006).</li>
<li>U.S. Energy Information Administration (2014). <a href="http://www.eia.gov/tools/faqs/faq.cfm?id=105&amp;t=3" class="uri">http://www.eia.gov/tools/faqs/faq.cfm?id=105&amp;t=3</a>. Accessed 5 July 2014.</li>
<li>United States Environmental Protection Agency (2015) <a href="https://www.epa.gov/sites/production/files/2015-02/documents/egrid_9th_edition_v1-0_year_2010_ghg_rates.pdf" class="uri">https://www.epa.gov/sites/production/files/2015-02/documents/egrid_9th_edition_v1-0_year_2010_ghg_rates.pdf</a>. Accessed 3 August 2016.</li>
<li>Climate Change Connection (2016). <a href="http://climatechangeconnection.org/emissions/co2-equivalents/" class="uri">http://climatechangeconnection.org/emissions/co2-equivalents/</a>. Accessed 3 August 2016.</li>
<li>Alternative Energy Store. (2008). Power ratings (typical) for common appliances. Available at <a href="http://www.altestore.com/howto/Tools-Calculators-Reference/Reference-Materials/Power-Ratings-typical-for-Common-Appliances/a21/" class="uri">http://www.altestore.com/howto/Tools-Calculators-Reference/Reference-Materials/Power-Ratings-typical-for-Common-Appliances/a21/</a>. Accessed 3 August 2016.</li>
<li>Silicon Valley Power. (2015). Appliance energy use chart. Available at <a href="http://www.siliconvalleypower.com/for-residents/save-energy/appliance-energy-use-chart" class="uri">http://www.siliconvalleypower.com/for-residents/save-energy/appliance-energy-use-chart</a>. Accessed 3 August 2016.</li>
<li>City Water Light &amp; Power. (2015). Appliance energy use chart. Available at <a href="http://www.cwlp.com/eso/efficiency101/appliancechart.html#chart" class="uri">http://www.cwlp.com/eso/efficiency101/appliancechart.html#chart</a>. Accessed 3 August 2016.</li>
<li>Efficiency Vermont (2015). Electric Usage Chart. Available at <a href="https://www.efficiencyvermont.com/For-My-Home/ways-to-save-and-rebates/Appliances/Refrigerators/General-Info/Electric-Usage-Chart" class="uri">https://www.efficiencyvermont.com/For-My-Home/ways-to-save-and-rebates/Appliances/Refrigerators/General-Info/Electric-Usage-Chart</a>. Accessed 3 August 2016.</li>
<li>Apex Solar (2016). <a href="http://www.apxsolar.com/downloads/5common_appliance_Wattages_.pdf" class="uri">http://www.apxsolar.com/downloads/5common_appliance_Wattages_.pdf</a>. Accessed 3 August 2016.</li>
<li>Eat For Health (2016). Serving Sizes. Available at: <a href="https://www.eatforhealth.gov.au/food-essentials/how-much-do-we-need-each-day/serve-sizes/" class="uri">https://www.eatforhealth.gov.au/food-essentials/how-much-do-we-need-each-day/serve-sizes/</a>. Accessed 3 August 2016.</li>
<li>United States Department of Agriculture (2016). USDA Food Composition Database. <a href="https://ndb.nal.usda.gov/ndb/foods/" class="uri">https://ndb.nal.usda.gov/ndb/foods/</a>. Accessed 3 August 2016.</li>
<li>Cordts, A., Nitzko, S. &amp; Spiller, A. Consumer response to negative information on meat consumption in Germany. <em>International Food and Agribusiness Management Review</em> <strong>17</strong>, 83-106 (2014).</li>
<li>Tobler, C., Visschers, V. H. &amp; Siegrist, M. Eating green. Consumers’ willingness to adopt ecological food consumption behaviors. <em>Appetite</em> <strong>57</strong>, 674-682 (2011).</li>
</ol>


<!-- -->

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/tegorman13\.github\.io\/llm_energy_task\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">## Supplementary Information</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>Camilleri, A. R., Larrick, R. P., Hossain, S., &amp; Patino-Echeverri, D. (2019). Consumers underestimate the emissions associated with food but are aided by labels. Nature Climate Change, 9(1), 53–58. https://doi.org/10.1038/s41558-018-0354-z</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">### Supplementary Note 1: Studies 1A and 1B Stimuli</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>**Study 1A Stimuli:**</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>*Page 1: Sampling Quota Questions*</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>What is your gender?</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Man</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Woman</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>What age group do you fall in?</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Under 18</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>18-24</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>25-34</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>35-44</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>45-54</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>55+</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>What is your ethnicity?</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>White</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>African American</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Asian</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Hispanic</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Other</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>*Page 2: Estimate of Household Energy Consumption*</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>Please answer the following using only prior knowledge.</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>Think about an average household in the United States. Now think about the total amount of energy that is used directly by that household in one year.</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>Consider that the energy used by a household can be divided into:</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Household operations: electricity, natural gas, and heating oil that is used for the house</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Transportation: air travel, motor travel, and public transportation used by people in the household</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Food production: growing and shipping food that people in the household eat.</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>What percentage of the total energy consumed per year by an average household in the United States is attributed to each of the following categories?</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>% household operations: <span class="co">[</span><span class="ot">slider bar response option ranging between 0 and 100</span><span class="co">]</span></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>% transportation: <span class="co">[</span><span class="ot">slider bar response option ranging between 0 and 100</span><span class="co">]</span></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>% food production: <span class="co">[</span><span class="ot">slider bar response option ranging between 0 and 100</span><span class="co">]</span></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>*Page 3: Appliance Energy Consumption*</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>Using a 100-watt incandescent light bulb for one hour consumes 100 units of energy.</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>Using this scale, how many units of energy do you think each of the following devices typically consumes when in use for one hour?</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>Enter a number less than 100 if you think the device consumes less energy than using a 100-watt bulb for an hour. Enter a number greater than 100 if you think the device consumes more energy than using a 100-watt bulb for an hour. For example, using two 100-watt incandescent bulbs for an hour would consume 200 units of energy.</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>Your best estimates are fine. Please enter whole numbers with no other text (no decimals, ranges, or percent signs).</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>Please respond carefully and thoughtfully (i.e., don't just put the same number for each item). If you do not answer carefully, your responses may be considered invalid.</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Units of energy for: A compact fluorescent light bulb that is as bright as a 100-watt incandescent light bulb</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Units of energy for: A desktop computer (including monitor)</span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Units of energy for: A laptop computer</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Units of energy for: An electric clothes dryer</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Units of energy for: A handheld clothes iron</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Units of energy for: A washing machine (excluding water)</span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Units of energy for: A portable electric heater</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Units of energy for: A room air-conditioner</span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Units of energy for: A central air-conditioner</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Units of energy for: A coffee maker</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Units of energy for: A dishwasher</span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Units of energy for: A freezer</span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Units of energy for: A refrigerator</span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Units of energy for: A toaster oven</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Units of energy for: A microwave oven</span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Units of energy for: A television</span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Units of energy for: A vacuum cleaner</span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Units of energy for: A DVD player</span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Units of energy for: Enter the number 100 in this box</span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a>*Page 4: Food Energy Consumption*</span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a>Using a 100-watt incandescent light bulb for one hour consumes 100 units of energy.</span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a>Using this scale, how many units of energy do you think each of the following foods consumes to produce and transport?</span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a>Enter a number less than 100 if you think the food's production and transport consumes less energy than using a 100-watt bulb for an hour. Enter a number greater than 100 if you think the food's production and transport consumes more energy than using a 100-watt bulb for an hour. For example, using two 100-watt incandescent bulbs for an hour would consume 200 units of energy.</span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a>Your best estimates are fine. Please enter whole numbers with no other text (no decimals, ranges, or percent signs).</span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a>Please respond carefully and thoughtfully (i.e., don't just put the same number for each item). If you do not answer carefully, your responses may be considered invalid.</span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Units of energy for: 1 small fist of lamb (0.22 lb)</span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Units of energy for: 1 small fist of beef (0.22 lb)</span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Units of energy for: 1 small fist of pork (0.22 lb)</span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Units of energy for: 2 slices of cheese (0.12 lb)</span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Units of energy for: 1 cup of milk (0.54 lb)</span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Units of energy for: 1 tofu steak (0.38 lb)</span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Units of energy for: A handful of almonds (0.16 lb)</span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Units of energy for: 2 large eggs (0.22 lb)</span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Units of energy for: 1 medium-sized potato (0.47 lb)</span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Units of energy for: 1 medium-sized apple (0.40 lb)</span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Units of energy for: 1 medium-sized orange (0.31 lb)</span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Units of energy for: 1 medium-sized tomato (0.27 lb)</span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Units of energy for: A handful of walnuts (0.14 lb)</span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Units of energy for: Half a cup of beans (0.20 lb)</span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Units of energy for: Half a cup of rice (0.20 lb)</span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Units of energy for: Half a cup of wheat (0.21 lb)</span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Units of energy for: Half a cup of barley (0.22 lb)</span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Units of energy for: Half a cup of soybeans (0.28 lb)</span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Units of energy for: Half a cup of maize / corn (0.16 lb)</span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Units of energy for: Enter the number 100 in this box</span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a>Notes:</span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Foods are listed as their approximate serving size.</span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Energy used includes production and transport from US manufacturer to distributor only and is based on an average distance of 1,500 miles travelled by a semi-trailer truck.</span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Energy from further processing, transport between distributor and retailer, consumption, and disposal are not included.</span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a>*Page 5: Attention Check Questions*</span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a>How many miles do you assume food is transported on average between manufacturer (e.g., farm) and distributor? <span class="sc">\_\_\_\_</span></span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a>According to the information on the previous page, how many units of energy are consumed by using a 100-watt incandescent light bulb for one hour?</span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>100 units</span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>500 units</span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>120 units</span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>80 units</span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a>*Page 6: Environmental Worldview*</span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">NEPr Scale questions listed - omitted here for brevity, standard 15 items</span><span class="co">]</span></span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a>*Page 7: Demographics*</span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Standard demographic questions: Age, Education, Employment Status, Household Income, Political Orientation (Economic &amp; Social), Political Affiliation - omitted here for brevity</span><span class="co">]</span></span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a>*Page 8: Conclusion*</span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a>Thank you for your participation!</span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a>If you have any reactions, comments, suggestions, hated some things, loved some things, or have spotted any problems with the questionnaire, then please provide them below. We really do value your feedback! <span class="sc">\_\_\_\_</span></span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a>**Study 1B Stimuli:**</span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a>*Pages 1 &amp; 2: Sampling Quota Questions and Estimate of Household GHG Emissions Source*</span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Identical to Study 1A, asking about GHG emissions instead of energy consumption</span><span class="co">]</span></span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a>*Page 3: Appliance GHG Emissions*</span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a>Using a 100-watt incandescent light bulb for one hour emits 100 units of greenhouse gas emissions.</span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a>Using this scale, how many units of greenhouse gas emissions do you think each of the following devices typically emits when in use for one hour?</span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Instructions similar to Study 1A, asking for GHG units</span><span class="co">]</span></span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">List of 18 appliances, identical to Study 1A</span><span class="co">]</span></span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a>Notes:</span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Emissions refers to carbon dioxide, methane, and nitrous oxide.</span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Emissions rate assumes 1.24 lb CO2-equivalent per kilowatt hour and an average of 7% electricity transmission loss.</span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a>*Page 4: Food GHG Emissions*</span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a>Using a 100-watt incandescent light bulb for one hour emits 100 units of greenhouse gas emissions.</span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a>Using this scale, how many units of greenhouse gas emissions do you think each of the following foods emits to produce and transport?</span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Instructions similar to Study 1A, asking for GHG units</span><span class="co">]</span></span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">List of 19 foods, identical to Study 1A</span><span class="co">]</span></span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a>Notes:</span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Foods are listed in terms of standard serving sizes.</span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Emissions refers to carbon dioxide, methane, and nitrous oxide.</span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Emissions includes production and transport from US manufacturer to distributor only and is based on an average distance of 1,500 miles travelled by a semi-trailer truck.</span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Emissions from further processing, transport between distributor and retailer, consumption, and disposal are not included.</span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a>*Page 5: Attention Check Questions*</span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a>How many miles do you assume food is transported on average between manufacturer (e.g., farm) and distributor? <span class="sc">\_\_\_\_</span></span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a>According to the information on the previous page, how many units of greenhouse gas emissions are emitted by using a 100-watt incandescent light bulb for one hour?</span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>100 units</span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>500 units</span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>120 units</span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>80 units</span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a>*Pages 6, 7, 8: Environmental Worldview, Demographics, Conclusion*</span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Identical to Study 1A</span><span class="co">]</span></span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a><span class="fu">### Supplementary Note 2: Studies 1C and 1D - Sensitivity of Results to Reference Unit</span></span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a>To examine the sensitivity of our findings to the reference unit used, we replicated Study 1A and 1B with a different sample and food reference unit. We randomly allocated 1,009 participants recruited from Amazon's Mechanical Turk to either Study 1C (estimating energy consumption) or Study 1D (estimating GHG emissions). The studies were available only to people in the United States. The materials and procedure were nearly identical to Study 1A and 1B except that the reference unit provided for energy consumption and GHG emissions was in terms of both a “medium-sized tomato” as well as the use of “a 100-watt incandescent light bulb for one hour". Both items were said to consume 100 units of energy (in Study 1C) or emit 100 units of GHG emissions (in Study 1D).</span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a>The 507 participants allocated to Study 1C ranged in age from 18 to 75 years with a mean of 33.5 (SD = 10.4). Among the survey respondents, 58% were female and 70% were employed full-time or part-time. Racially, 74% were non-Hispanic White, 6% Hispanic, 8% African American, and 10% Asian. Politically, 39% identified as Democrats, 38% as Independent, and 18% as Republican.</span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a>The 505 participants allocated to Study 1D ranged in age from 19 to 80 years with a mean of 34.5 (SD = 11.6). Among the survey respondents, 55% were female and 70% were employed full-time or part-time. Racially, 75% were non-Hispanic White, 5% Hispanic, 9% African American, and 9% Asian. Politically, 42% identified as Democrats, 32% as Independent, and 21% as Republican.</span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a>Figure S1 shows participants' estimated energy used plotted against actual energy consumed after transforming both distributions with base-10 logarithms to reduce positive skew. Figure S2 shows participants' estimated GHG emissions plotted against actual GHG emissions after transforming both distributions with base-10 logarithms to reduce positive skew. We ran the same mixed models as those reported in the main analysis. A summary of the models is provided in Table S1.</span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a>Compared to the main studies (that provided only an appliance reference unit), the replication studies (that provided both an appliance and a food reference unit) produced lines of best fit that were steeper and with less negative intercepts. Although the size of the difference between appliances and foods was reduced it remained statistically significant, thus supporting our main conclusion that consumers underestimate foods more than appliances.</span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a>*Figure S1: Mean estimates of energy used relative to actual energy used. The red fitted line depicts the relationship between the actual energy consumed throughout the life-cycle of 18 foods (x-axis) and the estimates provided by Study 1A participants (y-axis). The blue fitted line depicts the actual energy used of 18 electrical appliances (x-axis) and the estimates provided by Study 1A participants (y-axis). Accurate estimates would produce a set of points that fall along the grey 45-degree line. As shown, participants underestimated the energy consumption of all foods and almost all appliances (with the exception of CFL light bulbs, laptop computers, and DVD players). The underestimation was greater for foods than for appliances. Note that all estimates are expressed in terms of “Energy Units" and participants were told that producing and transporting a medium-sized tomato uses 100 Energy Units. All data are logged. Error bars represent the standard error of the mean.*</span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a>*Figure S2: Mean estimates of GHG emitted relative to actual GHG emitted. The red fitted line depicts the relationship between the actual GHG emitted throughout the life-cycle of 18 foods (x-axis) and the estimates provided by Study 1B participants (y-axis). The blue fitted line depicts the actual GHG emitted of 18 electrical appliances (x-axis) and the estimates provided by Study 1B participants (y-axis). Accurate estimates would produce a set of points that fall along the grey 45-degree line. As shown, participants underestimated the GHG emitted of all foods and almost all appliances (with the exception of CFL light bulbs, laptop computers, and DVD players). The underestimation was greater for foods than for appliances. Note that all estimates are expressed in terms of “Greenhouse Gas Units” and participants were told that producing and transporting a medium-sized tomato emits 100 Greenhouse Gas Units. All data are logged. Error bars represent the standard error of the mean.*</span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a>**Table S1.** Results of multilevel regressions for predicting consumers' perceptions of energy consumption (Study 1C) and greenhouse gas (GHG) emissions (Study 1D)</span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span>                          <span class="pp">|</span> Study 1C: Energy Consumption <span class="pp">|</span> Study 1C: Energy Consumption <span class="pp">|</span> Study 1D: GHG Emissions <span class="pp">|</span> Study 1D: GHG Emissions <span class="pp">|</span></span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a><span class="pp">|--------------------------|------------------------------|------------------------------|-------------------------|-------------------------|</span></span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span>                          <span class="pp">|</span> Eq. S1                       <span class="pp">|</span> Eq. S2                       <span class="pp">|</span> Eq. S3                  <span class="pp">|</span> Eq. S4                  <span class="pp">|</span></span>
<span id="cb1-187"><a href="#cb1-187" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Intercept                <span class="pp">|</span> -0.355<span class="sc">\*\*\*</span>                 <span class="pp">|</span> -0.333<span class="sc">\*\*\*</span>                 <span class="pp">|</span> -0.352<span class="sc">\*\*\*</span>            <span class="pp">|</span> -0.334<span class="sc">\*\*\*</span>            <span class="pp">|</span></span>
<span id="cb1-188"><a href="#cb1-188" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Domain (domain)          <span class="pp">|</span> -0.325<span class="sc">\*\*\*</span>                 <span class="pp">|</span> -0.381<span class="sc">\*\*\*</span>                 <span class="pp">|</span> -0.296<span class="sc">\*\*\*</span>            <span class="pp">|</span> -0.340<span class="sc">\*\*\*</span>            <span class="pp">|</span></span>
<span id="cb1-189"><a href="#cb1-189" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Log of actual value (actual)<span class="pp">|</span> 0.279<span class="sc">\*\*\*</span>                  <span class="pp">|</span> 0.236<span class="sc">\*\*\*</span>                  <span class="pp">|</span> 0.241<span class="sc">\*\*\*</span>             <span class="pp">|</span> 0.233<span class="sc">\*\*\*</span>             <span class="pp">|</span></span>
<span id="cb1-190"><a href="#cb1-190" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Quadratic term (actual²) <span class="pp">|</span> 0.025<span class="sc">\*\*</span>                    <span class="pp">|</span> -0.029<span class="sc">\*\*</span>                   <span class="pp">|</span> 0.010                   <span class="pp">|</span> -0.031<span class="sc">\*\*</span>              <span class="pp">|</span></span>
<span id="cb1-191"><a href="#cb1-191" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> domain<span class="sc">\*</span>actual           <span class="pp">|</span>                              <span class="pp">|</span> 0.107<span class="sc">\*\*\*</span>                  <span class="pp">|</span>                         <span class="pp">|</span> -0.007                  <span class="pp">|</span></span>
<span id="cb1-192"><a href="#cb1-192" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> domain<span class="sc">\*</span>actual²          <span class="pp">|</span>                              <span class="pp">|</span> 0.330<span class="sc">\*\*\*</span>                  <span class="pp">|</span>                         <span class="pp">|</span> 0.136<span class="sc">\*\*</span>               <span class="pp">|</span></span>
<span id="cb1-193"><a href="#cb1-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-194"><a href="#cb1-194" aria-hidden="true" tabindex="-1"></a>*Note: The independent variable domain refers to whether participants were estimating foods (coded "1") or appliances (coded “0”). The independent variable actual, which was logged and mean-centered, refers to the actual energy consumed or GHG emissions for each item. The dependent variable - estimated, which was also logged and centered relative to the mean of actual – refers to the participant's estimated energy consumed or GHG emissions for each item. Coefficients are unstandardized. \*\*\*p &lt; 0.001, \*\*p &lt; 0.01, \*p &lt; 0.05.*</span>
<span id="cb1-195"><a href="#cb1-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-196"><a href="#cb1-196" aria-hidden="true" tabindex="-1"></a>It is worth discussing one aspect of our study that may also have affected the participant's responses. Like previous research, we selected the energy consumed by a 100W light-bulb during one hour as a reference unit, which represents a relatively low energy consumption relative to the energy use of the items being evaluated. This low reference point is likely to have reduced overall estimates because people often make judgments that are too close to the reference point. Although the reference unit may tend to shift all estimates in aggregate, our primary focus was on the relative underestimation of food versus appliances. This inter-domain comparison is not influenced by the specific choice of reference unit. However, a potentially interesting future direction may be to examine between-domain behavior change preferences (e.g., willingness to eat less meat versus use less air conditioning).</span>
<span id="cb1-197"><a href="#cb1-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-198"><a href="#cb1-198" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb1-199"><a href="#cb1-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-200"><a href="#cb1-200" aria-hidden="true" tabindex="-1"></a><span class="fu">### Supplementary Note 3: Actual Life-Cycle Energy Use and GHG Emissions for Different Types of Food and Appliances</span></span>
<span id="cb1-201"><a href="#cb1-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-202"><a href="#cb1-202" aria-hidden="true" tabindex="-1"></a>The data sources for actual appliance energy use are shown in Table S2. The data reflect the best available information at the time of analysis. Because energy consumption of different appliances depends on its technical specifications, mode of use (e.g., a freezer will consume more electricity if doors are opened frequently), and environmental conditions (e.g., a freezer consumes more electricity if placed in a warmer room), no single estimate of power consumption is correct. In fact, several studies report ranges. However, to assess the accuracy of consumer's perceptions of energy consumption it is necessary to have a best estimate. To get such a value, when a range was given in a source, we used the middle value. When multiple values were available from different sources, we used the arithmetic mean. We then used the arithmetic mean of all sources to produce an “actual” value.</span>
<span id="cb1-203"><a href="#cb1-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-204"><a href="#cb1-204" aria-hidden="true" tabindex="-1"></a>The GHG emissions associated with energy consumption vary depending on the energy mix used in the power grid from which electricity is drawn, and the magnitude of energy losses in the power transmission and distribution. To obtain a best point-estimate of GHG emissions, we used the best-estimates of energy use and assumed: (a) electric power transmission resulted in a 7% loss of electricity, (b) 1.24 pounds of greenhouse gases were emitted per kWh consumed, and c) methane had 25 times the global warming potential of carbon dioxide while nitrous oxide's warming potential was 298 times that of carbon dioxide.</span>
<span id="cb1-205"><a href="#cb1-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-206"><a href="#cb1-206" aria-hidden="true" tabindex="-1"></a>Because it was possible that consumers would provide an estimate of energy use and GHG emissions that deviated from our “actual” value but was nevertheless within the range of values estimated from our sources, we performed a sensitivity analysis on these values (see Supplementary Note 4).</span>
<span id="cb1-207"><a href="#cb1-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-208"><a href="#cb1-208" aria-hidden="true" tabindex="-1"></a>**Table S2.** Data sources and actual values for energy consumed and GHG emissions released for using various appliances for one hour</span>
<span id="cb1-209"><a href="#cb1-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-210"><a href="#cb1-210" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Appliance              <span class="pp">|</span> Energy Consumed (W/hr) - Sources (AltE, SVP, CWLP, EV, AS) <span class="pp">|</span> Mean Energy (W/hr) <span class="pp">|</span> GHG Emissions (lb CO2 equiv / hr) <span class="pp">|</span> Energy/GHG Units<span class="sc">\*</span> <span class="pp">|</span></span>
<span id="cb1-211"><a href="#cb1-211" aria-hidden="true" tabindex="-1"></a><span class="pp">|------------------------|------------------------------------------------------------|--------------------|-----------------------------------|--------------------|</span></span>
<span id="cb1-212"><a href="#cb1-212" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Incandescent light bulb<span class="pp">|</span> 100, 100, 100, -, -                                        <span class="pp">|</span> 100                <span class="pp">|</span> 0.13                              <span class="pp">|</span> 100                <span class="pp">|</span></span>
<span id="cb1-213"><a href="#cb1-213" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> CFL light bulb         <span class="pp">|</span> 23, 27, 25, 22, -                                          <span class="pp">|</span> 24                 <span class="pp">|</span> 0.03                              <span class="pp">|</span> 24                 <span class="pp">|</span></span>
<span id="cb1-214"><a href="#cb1-214" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Desktop computer       <span class="pp">|</span> 80-200, 60-250, 90, -, 200                                  <span class="pp">|</span> 146                <span class="pp">|</span> 0.19                              <span class="pp">|</span> 146                <span class="pp">|</span></span>
<span id="cb1-215"><a href="#cb1-215" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Laptop computer        <span class="pp">|</span> 20-75, 20-50, -, -, -                                      <span class="pp">|</span> 41                 <span class="pp">|</span> 0.05                              <span class="pp">|</span> 41                 <span class="pp">|</span></span>
<span id="cb1-216"><a href="#cb1-216" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Electric clothes dryer <span class="pp">|</span> 4000, 2500-4000, 2700, 3125, 5000                           <span class="pp">|</span> 3615               <span class="pp">|</span> 4.79                              <span class="pp">|</span> 3615               <span class="pp">|</span></span>
<span id="cb1-217"><a href="#cb1-217" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Handheld clothes iron  <span class="pp">|</span> 1000, 1080, -, -, 1000                                     <span class="pp">|</span> 1027               <span class="pp">|</span> 1.36                              <span class="pp">|</span> 1027               <span class="pp">|</span></span>
<span id="cb1-218"><a href="#cb1-218" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Washing machine        <span class="pp">|</span> 500, -, 250, 281, 500                                      <span class="pp">|</span> 383                <span class="pp">|</span> 0.51                              <span class="pp">|</span> 383                <span class="pp">|</span></span>
<span id="cb1-219"><a href="#cb1-219" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Portable electric heater<span class="pp">|</span> 1500, 1500, 1500, 1500, 1200                               <span class="pp">|</span> 1440               <span class="pp">|</span> 1.91                              <span class="pp">|</span> 1440               <span class="pp">|</span></span>
<span id="cb1-220"><a href="#cb1-220" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Room air-conditioner   <span class="pp">|</span> 1000, 730-1800, -, 900, 750-1050                            <span class="pp">|</span> 1016               <span class="pp">|</span> 1.35                              <span class="pp">|</span> 1016               <span class="pp">|</span></span>
<span id="cb1-221"><a href="#cb1-221" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Central air-conditioner<span class="pp">|</span> 2000-5000, 3000, 850-6000, 3000, 3500                       <span class="pp">|</span> 3285               <span class="pp">|</span> 4.35                              <span class="pp">|</span> 3285               <span class="pp">|</span></span>
<span id="cb1-222"><a href="#cb1-222" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Coffee maker           <span class="pp">|</span> 800, 400, -, -, 900                                        <span class="pp">|</span> 700                <span class="pp">|</span> 0.93                              <span class="pp">|</span> 700                <span class="pp">|</span></span>
<span id="cb1-223"><a href="#cb1-223" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Dishwasher             <span class="pp">|</span> 1200-1500, 1000-2170, 1000, 500-800, 1300                  <span class="pp">|</span> 1177               <span class="pp">|</span> 1.56                              <span class="pp">|</span> 1177               <span class="pp">|</span></span>
<span id="cb1-224"><a href="#cb1-224" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Freezer                <span class="pp">|</span> 445, 125, 188, 49-166, 335                                  <span class="pp">|</span> 240                <span class="pp">|</span> 0.32                              <span class="pp">|</span> 240                <span class="pp">|</span></span>
<span id="cb1-225"><a href="#cb1-225" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Refrigerator           <span class="pp">|</span> 475, 77-333, 140-373, 44-188, 300-500                      <span class="pp">|</span> 291                <span class="pp">|</span> 0.38                              <span class="pp">|</span> 291                <span class="pp">|</span></span>
<span id="cb1-226"><a href="#cb1-226" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Toaster oven           <span class="pp">|</span> 800-1500, 750, -, -, 1150                                  <span class="pp">|</span> 1017               <span class="pp">|</span> 1.35                              <span class="pp">|</span> 1017               <span class="pp">|</span></span>
<span id="cb1-227"><a href="#cb1-227" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Microwave oven         <span class="pp">|</span> 600-1500, 1440, 750, 889, 1300                             <span class="pp">|</span> 1086               <span class="pp">|</span> 1.44                              <span class="pp">|</span> 1086               <span class="pp">|</span></span>
<span id="cb1-228"><a href="#cb1-228" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Television             <span class="pp">|</span> -, 12-480, 300, -, 180                                     <span class="pp">|</span> 242                <span class="pp">|</span> 0.32                              <span class="pp">|</span> 242                <span class="pp">|</span></span>
<span id="cb1-229"><a href="#cb1-229" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Vacuum cleaner         <span class="pp">|</span> 200-700, 750, -, -, 800                                    <span class="pp">|</span> 667                <span class="pp">|</span> 0.88                              <span class="pp">|</span> 667                <span class="pp">|</span></span>
<span id="cb1-230"><a href="#cb1-230" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> DVD player             <span class="pp">|</span> -, 30, -, 33, -                                            <span class="pp">|</span> 32                 <span class="pp">|</span> 0.04                              <span class="pp">|</span> 32                 <span class="pp">|</span></span>
<span id="cb1-231"><a href="#cb1-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-232"><a href="#cb1-232" aria-hidden="true" tabindex="-1"></a>*\* Described to participants as “Energy Units” and “GHG Emissions Units”*</span>
<span id="cb1-233"><a href="#cb1-233" aria-hidden="true" tabindex="-1"></a>*(Source keys: AltE, SVP, CWLP, EV, AS correspond to references in the original supplementary material)*</span>
<span id="cb1-234"><a href="#cb1-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-235"><a href="#cb1-235" aria-hidden="true" tabindex="-1"></a>Energy usage and GHG emissions associated with food production, processing, and transportation, depend on a large number of factors and hence, point-estimates of these impacts for generic foods are imprecise. For example, energy use and GHG emissions of vegetables depend on crop type, soil characteristics, hydro climatic conditions, pest and nutrient management, the use of irrigation, number of miles traveled, type of transportation, and storage technology. Nevertheless, our study required a best estimate for each food to compare to consumer perceptions. Our best estimates on energy use and associated GHG emissions of different foods were based on data from the LCA Software &amp; Carbon Footprint Analyzer FoodCarbonScopeTM, produced by the company CleanMetricsTM http://cleanmetrics.net/foodcarbonscope. FoodCarbonScopeTM is a web-based software tool for conducting Environmental Life Cycle Assessments of food. It provides estimates of life-cycle GHG emissions, energy use, and water use in food and beverage products, and has the largest commercially available life cycle inventory database for North American food production and processing. In May 2016 we were granted temporary access to the tool, which allowed us to search for foods that had data from multiple American sources, from which we took the arithmetic mean as our “actual” value. We estimated the serving size and serving size weight. A summary of this analysis is provided in Tables S3 and S4. Note that all values include 1,500 miles of transport by a semi-trailer.</span>
<span id="cb1-236"><a href="#cb1-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-237"><a href="#cb1-237" aria-hidden="true" tabindex="-1"></a>Because it is possible that consumers would provide an estimate of energy use and GHG emissions that deviated from our “actual” value but was nevertheless within the range of values estimated by different sources, we performed sensitivity analysis on these values (see Supplementary Note 4).</span>
<span id="cb1-238"><a href="#cb1-238" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-239"><a href="#cb1-239" aria-hidden="true" tabindex="-1"></a>**Table S3.** Data sources and actual values for energy consumed for producing and transporting various foods in Study 1.</span>
<span id="cb1-240"><a href="#cb1-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-241"><a href="#cb1-241" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Food      <span class="pp">|</span> Serving Size Description <span class="pp">|</span> Weight (lb) <span class="pp">|</span> Energy Consumed (MJ / kg) - Sources 1-4 <span class="pp">|</span> Mean Energy (MJ/kg) <span class="pp">|</span> Energy Units <span class="pp">|</span></span>
<span id="cb1-242"><a href="#cb1-242" aria-hidden="true" tabindex="-1"></a><span class="pp">|-----------|--------------------------|-------------|---------------------------------------|---------------------|--------------|</span></span>
<span id="cb1-243"><a href="#cb1-243" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Maize     <span class="pp">|</span> Half a cup of maize      <span class="pp">|</span> 0.16        <span class="pp">|</span> 4.78, 4.09, 4.16, 5.33                <span class="pp">|</span> 4.6                 <span class="pp">|</span> 93           <span class="pp">|</span></span>
<span id="cb1-244"><a href="#cb1-244" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Soybeans  <span class="pp">|</span> Half a cup of soybeans   <span class="pp">|</span> 0.28        <span class="pp">|</span> 5.14, 4.69, 5.00, 4.67                <span class="pp">|</span> 4.9                 <span class="pp">|</span> 173          <span class="pp">|</span></span>
<span id="cb1-245"><a href="#cb1-245" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Barley    <span class="pp">|</span> Half a cup of barley     <span class="pp">|</span> 0.22        <span class="pp">|</span> 5.67, 4.86, 6.04, 5.01                <span class="pp">|</span> 5.4                 <span class="pp">|</span> 150          <span class="pp">|</span></span>
<span id="cb1-246"><a href="#cb1-246" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Wheat     <span class="pp">|</span> Half a cup of wheat      <span class="pp">|</span> 0.21        <span class="pp">|</span> 4.39, 6.10, 5.25, 5.89                <span class="pp">|</span> 5.4                 <span class="pp">|</span> 144          <span class="pp">|</span></span>
<span id="cb1-247"><a href="#cb1-247" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Rice      <span class="pp">|</span> Half a cup of rice       <span class="pp">|</span> 0.20        <span class="pp">|</span> 9.81, 6.23, 11.56, 10.83              <span class="pp">|</span> 9.6                 <span class="pp">|</span> 247          <span class="pp">|</span></span>
<span id="cb1-248"><a href="#cb1-248" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Beans     <span class="pp">|</span> Half a cup of beans      <span class="pp">|</span> 0.20        <span class="pp">|</span> 9.04, 11.65, 10.70, 11.19             <span class="pp">|</span> 10.6                <span class="pp">|</span> 272          <span class="pp">|</span></span>
<span id="cb1-249"><a href="#cb1-249" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Walnuts   <span class="pp">|</span> A handful of walnuts     <span class="pp">|</span> 0.14        <span class="pp">|</span> 12.42, 13.04, -, -                    <span class="pp">|</span> 12.7                <span class="pp">|</span> 220          <span class="pp">|</span></span>
<span id="cb1-250"><a href="#cb1-250" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Tomatoes  <span class="pp">|</span> 1 medium-sized tomato    <span class="pp">|</span> 0.27        <span class="pp">|</span> 3.72, 5.25, 5.14, 5.25                <span class="pp">|</span> 4.8                 <span class="pp">|</span> 165          <span class="pp">|</span></span>
<span id="cb1-251"><a href="#cb1-251" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Oranges   <span class="pp">|</span> 1 medium-sized orange    <span class="pp">|</span> 0.31        <span class="pp">|</span> 3.45, 4.09, 4.11, -                   <span class="pp">|</span> 3.9                 <span class="pp">|</span> 151          <span class="pp">|</span></span>
<span id="cb1-252"><a href="#cb1-252" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Apples    <span class="pp">|</span> 1 medium-sized apple     <span class="pp">|</span> 0.40        <span class="pp">|</span> 4.64, 6.86, 4.05, 5.36                <span class="pp">|</span> 5.2                 <span class="pp">|</span> 264          <span class="pp">|</span></span>
<span id="cb1-253"><a href="#cb1-253" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Potatoes  <span class="pp">|</span> 1 medium-sized potato    <span class="pp">|</span> 0.47        <span class="pp">|</span> 7.02, 4.55, 6.71, 8.74                <span class="pp">|</span> 6.8                 <span class="pp">|</span> 399          <span class="pp">|</span></span>
<span id="cb1-254"><a href="#cb1-254" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Eggs      <span class="pp">|</span> 2 large eggs             <span class="pp">|</span> 0.22        <span class="pp">|</span> 19.51, 17.60, -, -                    <span class="pp">|</span> 18.6                <span class="pp">|</span> 516          <span class="pp">|</span></span>
<span id="cb1-255"><a href="#cb1-255" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Almonds   <span class="pp">|</span> A handful of almonds     <span class="pp">|</span> 0.16        <span class="pp">|</span> 23.76, 33.63, 34.18, 47.89            <span class="pp">|</span> 34.9                <span class="pp">|</span> 692          <span class="pp">|</span></span>
<span id="cb1-256"><a href="#cb1-256" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Tofu      <span class="pp">|</span> 1 tofu steak             <span class="pp">|</span> 0.38        <span class="pp">|</span> 9.14, 8.86, -, -                      <span class="pp">|</span> 9.0                 <span class="pp">|</span> 425          <span class="pp">|</span></span>
<span id="cb1-257"><a href="#cb1-257" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Milk      <span class="pp">|</span> 1 cup of milk            <span class="pp">|</span> 0.54        <span class="pp">|</span> 5.82, 6.57, 6.17, 8.36                <span class="pp">|</span> 6.7                 <span class="pp">|</span> 456          <span class="pp">|</span></span>
<span id="cb1-258"><a href="#cb1-258" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Cheese    <span class="pp">|</span> 2 slices of cheese       <span class="pp">|</span> 0.12        <span class="pp">|</span> 43.25, 43.01, -, -                    <span class="pp">|</span> 43.1                <span class="pp">|</span> 672          <span class="pp">|</span></span>
<span id="cb1-259"><a href="#cb1-259" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Pork      <span class="pp">|</span> A small fist of pork     <span class="pp">|</span> 0.22        <span class="pp">|</span> 29.46, 27.57, 33.21, 37.06            <span class="pp">|</span> 31.8                <span class="pp">|</span> 884          <span class="pp">|</span></span>
<span id="cb1-260"><a href="#cb1-260" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Beef      <span class="pp">|</span> A small fist of beef     <span class="pp">|</span> 0.22        <span class="pp">|</span> 37.03, 50.22, 79.42, -                <span class="pp">|</span> 55.6                <span class="pp">|</span> 1544         <span class="pp">|</span></span>
<span id="cb1-261"><a href="#cb1-261" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Lamb      <span class="pp">|</span> A small fist of lamb     <span class="pp">|</span> 0.22        <span class="pp">|</span> 70.29, 64.89, 70.32, -                <span class="pp">|</span> 68.5                <span class="pp">|</span> 1904         <span class="pp">|</span></span>
<span id="cb1-262"><a href="#cb1-262" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-263"><a href="#cb1-263" aria-hidden="true" tabindex="-1"></a>**Table S4.** Data sources and actual values for GHG emissions released in producing and transporting various foods in Study 1.</span>
<span id="cb1-264"><a href="#cb1-264" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-265"><a href="#cb1-265" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Food      <span class="pp">|</span> Serving Size Description <span class="pp">|</span> Weight (lb) <span class="pp">|</span> GHG Emissions (kg CO2 equiv. / kg) - Sources 1-4 <span class="pp">|</span> Mean GHG (kg CO2e/kg) <span class="pp">|</span> lb CO2e / serv. <span class="pp">|</span> GHG Emission Units <span class="pp">|</span></span>
<span id="cb1-266"><a href="#cb1-266" aria-hidden="true" tabindex="-1"></a><span class="pp">|-----------|--------------------------|-------------|----------------------------------------------------|-----------------------|-----------------|--------------------|</span></span>
<span id="cb1-267"><a href="#cb1-267" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Maize     <span class="pp">|</span> Half a cup of maize      <span class="pp">|</span> 0.16        <span class="pp">|</span> 0.52, 0.43, 0.41, 0.61                             <span class="pp">|</span> 0.49                  <span class="pp">|</span> 0.08            <span class="pp">|</span> 59                 <span class="pp">|</span></span>
<span id="cb1-268"><a href="#cb1-268" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Soybeans  <span class="pp">|</span> Half a cup of soybeans   <span class="pp">|</span> 0.28        <span class="pp">|</span> 0.78, 0.75, 0.77, 0.64                             <span class="pp">|</span> 0.74                  <span class="pp">|</span> 0.21            <span class="pp">|</span> 156                <span class="pp">|</span></span>
<span id="cb1-269"><a href="#cb1-269" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Barley    <span class="pp">|</span> Half a cup of barley     <span class="pp">|</span> 0.22        <span class="pp">|</span> 0.50, 0.48, 0.53, 0.46                             <span class="pp">|</span> 0.49                  <span class="pp">|</span> 0.11            <span class="pp">|</span> 82                 <span class="pp">|</span></span>
<span id="cb1-270"><a href="#cb1-270" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Wheat     <span class="pp">|</span> Half a cup of wheat      <span class="pp">|</span> 0.21        <span class="pp">|</span> 0.50, 0.59, 0.53, 0.53                             <span class="pp">|</span> 0.54                  <span class="pp">|</span> 0.11            <span class="pp">|</span> 86                 <span class="pp">|</span></span>
<span id="cb1-271"><a href="#cb1-271" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Rice      <span class="pp">|</span> Half a cup of rice       <span class="pp">|</span> 0.20        <span class="pp">|</span> 2.25, 1.71, 2.53, 2.34                             <span class="pp">|</span> 2.21                  <span class="pp">|</span> 0.45            <span class="pp">|</span> 339                <span class="pp">|</span></span>
<span id="cb1-272"><a href="#cb1-272" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Beans     <span class="pp">|</span> Half a cup of beans      <span class="pp">|</span> 0.20        <span class="pp">|</span> 1.00, 0.98, 0.93, 1.21                             <span class="pp">|</span> 1.03                  <span class="pp">|</span> 0.21            <span class="pp">|</span> 158                <span class="pp">|</span></span>
<span id="cb1-273"><a href="#cb1-273" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Walnuts   <span class="pp">|</span> A handful of walnuts     <span class="pp">|</span> 0.14        <span class="pp">|</span> 0.94, 1.09, -, -                                   <span class="pp">|</span> 1.02                  <span class="pp">|</span> 0.14            <span class="pp">|</span> 105                <span class="pp">|</span></span>
<span id="cb1-274"><a href="#cb1-274" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Tomatoes  <span class="pp">|</span> 1 medium-sized tomato    <span class="pp">|</span> 0.27        <span class="pp">|</span> 0.30, 0.42, 0.52, 0.42                             <span class="pp">|</span> 0.42                  <span class="pp">|</span> 0.11            <span class="pp">|</span> 85                 <span class="pp">|</span></span>
<span id="cb1-275"><a href="#cb1-275" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Oranges   <span class="pp">|</span> 1 medium-sized orange    <span class="pp">|</span> 0.31        <span class="pp">|</span> 0.28, 0.30, 0.31, -                                <span class="pp">|</span> 0.30                  <span class="pp">|</span> 0.09            <span class="pp">|</span> 69                 <span class="pp">|</span></span>
<span id="cb1-276"><a href="#cb1-276" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Apples    <span class="pp">|</span> 1 medium-sized apple     <span class="pp">|</span> 0.40        <span class="pp">|</span> 0.34, 0.46, 0.29, 0.37                             <span class="pp">|</span> 0.37                  <span class="pp">|</span> 0.15            <span class="pp">|</span> 110                <span class="pp">|</span></span>
<span id="cb1-277"><a href="#cb1-277" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Potatoes  <span class="pp">|</span> 1 medium-sized potato    <span class="pp">|</span> 0.47        <span class="pp">|</span> 0.51, 0.37, 0.51, 0.64                             <span class="pp">|</span> 0.51                  <span class="pp">|</span> 0.24            <span class="pp">|</span> 179                <span class="pp">|</span></span>
<span id="cb1-278"><a href="#cb1-278" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Eggs      <span class="pp">|</span> 2 large eggs             <span class="pp">|</span> 0.22        <span class="pp">|</span> 2.04, 2.07, -, -                                   <span class="pp">|</span> 2.06                  <span class="pp">|</span> 0.45            <span class="pp">|</span> 341                <span class="pp">|</span></span>
<span id="cb1-279"><a href="#cb1-279" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Almonds   <span class="pp">|</span> A handful of almonds     <span class="pp">|</span> 0.16        <span class="pp">|</span> 2.07, 2.63, 2.65, 3.75                             <span class="pp">|</span> 2.78                  <span class="pp">|</span> 0.44            <span class="pp">|</span> 329                <span class="pp">|</span></span>
<span id="cb1-280"><a href="#cb1-280" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Tofu      <span class="pp">|</span> 1 tofu steak             <span class="pp">|</span> 0.38        <span class="pp">|</span> 0.89, 0.87, -, -                                   <span class="pp">|</span> 0.88                  <span class="pp">|</span> 0.33            <span class="pp">|</span> 248                <span class="pp">|</span></span>
<span id="cb1-281"><a href="#cb1-281" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Milk      <span class="pp">|</span> 1 cup of milk            <span class="pp">|</span> 0.54        <span class="pp">|</span> 1.20, 1.28, 1.34, 1.90                             <span class="pp">|</span> 1.43                  <span class="pp">|</span> 0.77            <span class="pp">|</span> 579                <span class="pp">|</span></span>
<span id="cb1-282"><a href="#cb1-282" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Cheese    <span class="pp">|</span> 2 slices of cheese       <span class="pp">|</span> 0.12        <span class="pp">|</span> 10.02, 10.00, -, -                                 <span class="pp">|</span> 10.01                 <span class="pp">|</span> 1.24            <span class="pp">|</span> 933                <span class="pp">|</span></span>
<span id="cb1-283"><a href="#cb1-283" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Pork      <span class="pp">|</span> A small fist of pork     <span class="pp">|</span> 0.22        <span class="pp">|</span> 4.80, 4.46, 5.14, 5.79                             <span class="pp">|</span> 5.05                  <span class="pp">|</span> 1.11            <span class="pp">|</span> 838                <span class="pp">|</span></span>
<span id="cb1-284"><a href="#cb1-284" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Beef      <span class="pp">|</span> A small fist of beef     <span class="pp">|</span> 0.22        <span class="pp">|</span> 12.94, 14.57, 17.31, -                             <span class="pp">|</span> 14.94                 <span class="pp">|</span> 3.29            <span class="pp">|</span> 2481               <span class="pp">|</span></span>
<span id="cb1-285"><a href="#cb1-285" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Lamb      <span class="pp">|</span> A small fist of lamb     <span class="pp">|</span> 0.22        <span class="pp">|</span> 20.66, 18.63, 24.61, -                             <span class="pp">|</span> 21.30                 <span class="pp">|</span> 4.69            <span class="pp">|</span> 3538               <span class="pp">|</span></span>
<span id="cb1-286"><a href="#cb1-286" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-287"><a href="#cb1-287" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb1-288"><a href="#cb1-288" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-289"><a href="#cb1-289" aria-hidden="true" tabindex="-1"></a><span class="fu">### Supplementary Note 4: Studies 1A and 1B - Testing Additional Covariates and Sensitivity of Results to Assumed Actual Values</span></span>
<span id="cb1-290"><a href="#cb1-290" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-291"><a href="#cb1-291" aria-hidden="true" tabindex="-1"></a>A within-subjects t-test revealed that the mean individual-level correlation between perceived and actual values was significantly low for foods than for appliances for energy use (Mappliances = .31, SD = .27, vs. Mfood = .24, SD = .25), t(517) = 4.77, p &lt; .0001, and GHG emissions (Mappliances = .28, SD = .28, vs. Mfood= .24, SD = .28), t(513) = 2.18, p = .03. We note that the food items used in our study had a more restricted range of “actual” values (e.g., lowest energy = 93 energy units; highest energy = 1904 energy units) compared to appliances (lowest energy = 32 energy units; highest energy = 3,615 energy units), which can reduce correlations.</span>
<span id="cb1-292"><a href="#cb1-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-293"><a href="#cb1-293" aria-hidden="true" tabindex="-1"></a>In order to examine the effect of covariates in Study 1A and 1B, we ran the same mixed-effect models as described in the main text a second time, now including all of the demographic variables (i.e., Gender <span class="co">[</span><span class="ot">“Male” reference level</span><span class="co">]</span>, Age, Ethnicity <span class="co">[</span><span class="ot">“Other” reference level</span><span class="co">]</span>, Education, Employment <span class="co">[</span><span class="ot">“Homemaker” reference level</span><span class="co">]</span>, Income, Political Orientation – Economic Issues, Political Orientation – Social Issues, Political Party <span class="co">[</span><span class="ot">“Other" reference level</span><span class="co">]</span>, NEPr (i.e., environmental worldview), and Order as covariates. A summary of the models is provided in Table S5.</span>
<span id="cb1-294"><a href="#cb1-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-295"><a href="#cb1-295" aria-hidden="true" tabindex="-1"></a>In Study 1A, in addition to the effects described in the main analysis, there was a significant effect of NEPr indicating that estimates were higher for those who had a more pro-environmental worldview. This observation is consistent with prior research.</span>
<span id="cb1-296"><a href="#cb1-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-297"><a href="#cb1-297" aria-hidden="true" tabindex="-1"></a>In Study 1B, in addition to the effects described in the main analysis, there was a significant effect of NEPr again indicating that estimates were higher for those who had a more pro-environmental worldview. There was a significant effect of gender indicating that estimates were higher for those who were female. This observation is consistent with some prior research (but not all). There was a significant effect of education indicating that estimates were higher for those who were more educated. There was a significant effect of income indicating that estimates were higher for those who reported a higher family income bracket.</span>
<span id="cb1-298"><a href="#cb1-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-299"><a href="#cb1-299" aria-hidden="true" tabindex="-1"></a>**Table S5.** Results of multilevel regressions for predicting consumers' perceptions of energy consumption (Study 1B) and greenhouse gas (GHG) emissions (Study 1B) including covariates.</span>
<span id="cb1-300"><a href="#cb1-300" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-301"><a href="#cb1-301" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Predictor Variable                      <span class="pp">|</span> Study 1A: Energy Consumption <span class="pp">|</span> Study 1B: GHG Emissions <span class="pp">|</span></span>
<span id="cb1-302"><a href="#cb1-302" aria-hidden="true" tabindex="-1"></a><span class="pp">|-----------------------------------------|-----------------------------|------------------------|</span></span>
<span id="cb1-303"><a href="#cb1-303" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Intercept                               <span class="pp">|</span> -0.952<span class="sc">\*</span>                    <span class="pp">|</span> -1.149<span class="sc">\*\*\*</span>           <span class="pp">|</span></span>
<span id="cb1-304"><a href="#cb1-304" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Domain (domain)                         <span class="pp">|</span> -0.530<span class="sc">\*\*\*</span>                <span class="pp">|</span> -0.509<span class="sc">\*\*\*</span>           <span class="pp">|</span></span>
<span id="cb1-305"><a href="#cb1-305" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Log of actual value (actual)            <span class="pp">|</span> 0.210<span class="sc">\*\*\*</span>                 <span class="pp">|</span> 0.176<span class="sc">\*\*\*</span>            <span class="pp">|</span></span>
<span id="cb1-306"><a href="#cb1-306" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Quadratic term (actual²)                <span class="pp">|</span> 0.025<span class="sc">\*</span>                     <span class="pp">|</span> 0.010                  <span class="pp">|</span></span>
<span id="cb1-307"><a href="#cb1-307" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> domain<span class="sc">\*</span>actual                          <span class="pp">|</span> -0.033<span class="sc">\*</span>                    <span class="pp">|</span> -0.062<span class="sc">\*\*\*</span>           <span class="pp">|</span></span>
<span id="cb1-308"><a href="#cb1-308" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> domain<span class="sc">\*</span> actual²                        <span class="pp">|</span> 0.421<span class="sc">\*\*\*</span>                 <span class="pp">|</span> 0.132<span class="sc">\*\*\*</span>            <span class="pp">|</span></span>
<span id="cb1-309"><a href="#cb1-309" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Gender                                  <span class="pp">|</span> 0.029                       <span class="pp">|</span> -0.131<span class="sc">\*</span>               <span class="pp">|</span></span>
<span id="cb1-310"><a href="#cb1-310" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Age                                     <span class="pp">|</span> -0.005                      <span class="pp">|</span> -0.002                 <span class="pp">|</span></span>
<span id="cb1-311"><a href="#cb1-311" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Ethnicity <span class="co">[</span><span class="ot">White</span><span class="co">]</span>                       <span class="pp">|</span> -0.047                      <span class="pp">|</span> -0.085                 <span class="pp">|</span></span>
<span id="cb1-312"><a href="#cb1-312" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Ethnicity <span class="co">[</span><span class="ot">African American</span><span class="co">]</span>            <span class="pp">|</span> -0.172                      <span class="pp">|</span> -0.025                 <span class="pp">|</span></span>
<span id="cb1-313"><a href="#cb1-313" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Ethnicity <span class="co">[</span><span class="ot">Asian</span><span class="co">]</span>                       <span class="pp">|</span> 0.169                       <span class="pp">|</span> -0.098                 <span class="pp">|</span></span>
<span id="cb1-314"><a href="#cb1-314" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Ethnicity <span class="co">[</span><span class="ot">Hispanic</span><span class="co">]</span>                    <span class="pp">|</span> 0.011                       <span class="pp">|</span> -0.087                 <span class="pp">|</span></span>
<span id="cb1-315"><a href="#cb1-315" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Education                               <span class="pp">|</span> 0.012                       <span class="pp">|</span> 0.043<span class="sc">\*</span>                <span class="pp">|</span></span>
<span id="cb1-316"><a href="#cb1-316" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Employment <span class="co">[</span><span class="ot">Employed full time</span><span class="co">]</span>         <span class="pp">|</span> 0.028                       <span class="pp">|</span> -0.110                 <span class="pp">|</span></span>
<span id="cb1-317"><a href="#cb1-317" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Employment <span class="co">[</span><span class="ot">Employed part time</span><span class="co">]</span>         <span class="pp">|</span> 0.127                       <span class="pp">|</span> -0.064                 <span class="pp">|</span></span>
<span id="cb1-318"><a href="#cb1-318" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Employment <span class="co">[</span><span class="ot">Not employed but looking</span><span class="co">]</span>   <span class="pp">|</span> -0.092                      <span class="pp">|</span> 0.018                  <span class="pp">|</span></span>
<span id="cb1-319"><a href="#cb1-319" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Employment <span class="co">[</span><span class="ot">Not employed and not looking</span><span class="co">]</span><span class="pp">|</span> 0.062                       <span class="pp">|</span> 0.009                  <span class="pp">|</span></span>
<span id="cb1-320"><a href="#cb1-320" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Employment <span class="co">[</span><span class="ot">Retired</span><span class="co">]</span>                    <span class="pp">|</span> 0.006                       <span class="pp">|</span> 0.033                  <span class="pp">|</span></span>
<span id="cb1-321"><a href="#cb1-321" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Employment <span class="co">[</span><span class="ot">Student</span><span class="co">]</span>                    <span class="pp">|</span> 0.080                       <span class="pp">|</span> 0.030                  <span class="pp">|</span></span>
<span id="cb1-322"><a href="#cb1-322" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Income                                  <span class="pp">|</span> 0.009                       <span class="pp">|</span> 0.039<span class="sc">\*</span>                <span class="pp">|</span></span>
<span id="cb1-323"><a href="#cb1-323" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Political Orientation – Economic Issues <span class="pp">|</span> 0.029                       <span class="pp">|</span> 0.011                  <span class="pp">|</span></span>
<span id="cb1-324"><a href="#cb1-324" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Political Orientation – Social Issues   <span class="pp">|</span> -0.041                      <span class="pp">|</span> -0.010                 <span class="pp">|</span></span>
<span id="cb1-325"><a href="#cb1-325" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Political Party <span class="co">[</span><span class="ot">Democrat</span><span class="co">]</span>              <span class="pp">|</span> -0.020                      <span class="pp">|</span> -0.193                 <span class="pp">|</span></span>
<span id="cb1-326"><a href="#cb1-326" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Political Party <span class="co">[</span><span class="ot">Independent</span><span class="co">]</span>           <span class="pp">|</span> -0.034                      <span class="pp">|</span> -0.121                 <span class="pp">|</span></span>
<span id="cb1-327"><a href="#cb1-327" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Political Party <span class="co">[</span><span class="ot">Republican</span><span class="co">]</span>            <span class="pp">|</span> -0.142                      <span class="pp">|</span> -0.069                 <span class="pp">|</span></span>
<span id="cb1-328"><a href="#cb1-328" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> NEPr                                    <span class="pp">|</span> 0.008<span class="sc">\*</span>                     <span class="pp">|</span> 0.010<span class="sc">\*\*</span>              <span class="pp">|</span></span>
<span id="cb1-329"><a href="#cb1-329" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Order                                   <span class="pp">|</span> 0.031                       <span class="pp">|</span> -0.106<span class="sc">\*</span>               <span class="pp">|</span></span>
<span id="cb1-330"><a href="#cb1-330" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-331"><a href="#cb1-331" aria-hidden="true" tabindex="-1"></a>*Note: Coefficients are unstandardized. \*\*\*p &lt;0.001, \*\*p &lt; 0.01, \*p &lt; 0.05.*</span>
<span id="cb1-332"><a href="#cb1-332" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-333"><a href="#cb1-333" aria-hidden="true" tabindex="-1"></a>To examine the sensitivity of our findings to the *actual* values, we re-ran all analyses reported in the main text for Study 1A and 1B assuming energy consumption and GHG emissions of food and appliances was equal to the minimum rather than the average of the values reported by the different sources.</span>
<span id="cb1-334"><a href="#cb1-334" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-335"><a href="#cb1-335" aria-hidden="true" tabindex="-1"></a>Figure S3 shows participants' estimated energy used plotted against conservative actual energy consumed after transforming both distributions with base-10 logarithms to reduce positive skew. Figure S4 shows participants' estimated GHG emissions plotted against conservative actual GHG emissions after transforming both distributions with base-10 logarithms to reduce positive skew. We ran the same mixed models as those reported in the main analysis. A summary of the models is provided in Table S6.</span>
<span id="cb1-336"><a href="#cb1-336" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-337"><a href="#cb1-337" aria-hidden="true" tabindex="-1"></a>Compared to the main analysis, the conservative analysis produced lines of best fit that were shallower and with less negative intercepts. Importantly, the size of the difference between appliances and foods was very similar between analyses, supporting our main conclusion that consumers underestimate foods more than appliances.</span>
<span id="cb1-338"><a href="#cb1-338" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-339"><a href="#cb1-339" aria-hidden="true" tabindex="-1"></a>*Figure S3: Mean estimates of energy used relative to conservative actual energy used. The red fitted line depicts the relationship between the conservative actual energy consumed throughout the life-cycle of 19 foods (x-axis) and the estimates provided by Study 1A participants (y-axis). The blue fitted line depicts the conservative actual energy used of 18 electrical appliances (x-axis) and the estimates provided by Study 1A participants (y-axis)...*</span>
<span id="cb1-340"><a href="#cb1-340" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-341"><a href="#cb1-341" aria-hidden="true" tabindex="-1"></a>*Figure S4: Mean estimates of GHG emitted relative to conservative actual GHG emitted. The red fitted line depicts the relationship between the conservative actual GHG emitted throughout the life-cycle of 19 foods (x-axis) and the estimates provided by Study 1B participants (y-axis). The blue fitted line depicts the conservative actual GHG emitted of 18 electrical appliances (x-axis) and the estimates provided by Study 1B participants (y-axis)...*</span>
<span id="cb1-342"><a href="#cb1-342" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-343"><a href="#cb1-343" aria-hidden="true" tabindex="-1"></a>**Table S6.** Results of multilevel regressions for predicting consumers' perceptions of energy consumption (Study 1A) and greenhouse gas (GHG) emissions (Study 1B) relative to conservative actual values</span>
<span id="cb1-344"><a href="#cb1-344" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-345"><a href="#cb1-345" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span>                          <span class="pp">|</span> Study 1A: Energy Consumption <span class="pp">|</span> Study 1A: Energy Consumption <span class="pp">|</span> Study 1B: GHG Emissions <span class="pp">|</span> Study 1B: GHG Emissions <span class="pp">|</span></span>
<span id="cb1-346"><a href="#cb1-346" aria-hidden="true" tabindex="-1"></a><span class="pp">|--------------------------|------------------------------|------------------------------|-------------------------|-------------------------|</span></span>
<span id="cb1-347"><a href="#cb1-347" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span>                          <span class="pp">|</span> Eq. S1                       <span class="pp">|</span> Eq. S2                       <span class="pp">|</span> Eq. S3                  <span class="pp">|</span> Eq. S4                  <span class="pp">|</span></span>
<span id="cb1-348"><a href="#cb1-348" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Intercept                <span class="pp">|</span> -0.512<span class="sc">\*\*\*</span>                 <span class="pp">|</span> -0.486<span class="sc">\*\*\*</span>                 <span class="pp">|</span> -0.492<span class="sc">\*\*\*</span>            <span class="pp">|</span> -0.504<span class="sc">\*\*\*</span>            <span class="pp">|</span></span>
<span id="cb1-349"><a href="#cb1-349" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Domain (domain)          <span class="pp">|</span> -0.484<span class="sc">\*\*\*</span>                 <span class="pp">|</span> -0.546<span class="sc">\*\*\*</span>                 <span class="pp">|</span> -0.509<span class="sc">\*\*\*</span>            <span class="pp">|</span> -0.484<span class="sc">\*\*\*</span>            <span class="pp">|</span></span>
<span id="cb1-350"><a href="#cb1-350" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Log of actual value (actual)<span class="pp">|</span> 0.153<span class="sc">\*\*\*</span>                  <span class="pp">|</span> 0.130<span class="sc">\*\*\*</span>                  <span class="pp">|</span> 0.086<span class="sc">\*\*\*</span>             <span class="pp">|</span> 0.094<span class="sc">\*\*\*</span>             <span class="pp">|</span></span>
<span id="cb1-351"><a href="#cb1-351" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Quadratic term (actual²) <span class="pp">|</span> 0.120<span class="sc">\*\*\*</span>                  <span class="pp">|</span> 0.066<span class="sc">\*\*\*</span>                  <span class="pp">|</span> 0.015<span class="sc">\*\*\*</span>             <span class="pp">|</span> 0.039<span class="sc">\*\*\*</span>             <span class="pp">|</span></span>
<span id="cb1-352"><a href="#cb1-352" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> domain<span class="sc">\*</span>actual           <span class="pp">|</span>                              <span class="pp">|</span> -0.086<span class="sc">\*\*\*</span>                 <span class="pp">|</span>                         <span class="pp">|</span> 0.006                   <span class="pp">|</span></span>
<span id="cb1-353"><a href="#cb1-353" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> domain<span class="sc">\*</span>actual²          <span class="pp">|</span>                              <span class="pp">|</span> 0.404<span class="sc">\*\*\*</span>                  <span class="pp">|</span>                         <span class="pp">|</span> -0.074<span class="sc">\*\*</span>              <span class="pp">|</span></span>
<span id="cb1-354"><a href="#cb1-354" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-355"><a href="#cb1-355" aria-hidden="true" tabindex="-1"></a>*Note: Coefficients are unstandardized. \*\*\*p &lt; 0.001, \*\*p &lt; 0.01, \*p &lt; 0.05.*</span>
<span id="cb1-356"><a href="#cb1-356" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-357"><a href="#cb1-357" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb1-358"><a href="#cb1-358" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-359"><a href="#cb1-359" aria-hidden="true" tabindex="-1"></a><span class="fu">### Supplementary Note 5: Study 2 Stimuli</span></span>
<span id="cb1-360"><a href="#cb1-360" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-361"><a href="#cb1-361" aria-hidden="true" tabindex="-1"></a>*Demographics [These questions were asked prior to the bundle of studies being carried out]*</span>
<span id="cb1-362"><a href="#cb1-362" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Standard demographic questions: Age, Gender, Ethnicity/Race, Student Status, Employment Status, Political Views, Education Level, Household Income, Religious Affiliation, English Proficiency, Time in US - omitted here for brevity</span><span class="co">]</span></span>
<span id="cb1-363"><a href="#cb1-363" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-364"><a href="#cb1-364" aria-hidden="true" tabindex="-1"></a>*Page 1: Instructions*</span>
<span id="cb1-365"><a href="#cb1-365" aria-hidden="true" tabindex="-1"></a>For completing this particular study, you will earn $6. However, $3 of this payment must be spent during this study to purchase goods of your choosing. You will actually get these goods (in addition to your cash payment) at the end of the study.</span>
<span id="cb1-366"><a href="#cb1-366" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-367"><a href="#cb1-367" aria-hidden="true" tabindex="-1"></a>*Page 2: Choice*</span>
<span id="cb1-368"><a href="#cb1-368" aria-hidden="true" tabindex="-1"></a>In this study, you will be buying soup and the following options are available to you.</span>
<span id="cb1-369"><a href="#cb1-369" aria-hidden="true" tabindex="-1"></a>Note that there are 6 options and they are arranged in two rows.</span>
<span id="cb1-370"><a href="#cb1-370" aria-hidden="true" tabindex="-1"></a>At the end of the study, you will actually receive the cans of soup you buy.</span>
<span id="cb1-371"><a href="#cb1-371" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-372"><a href="#cb1-372" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Table showing 6 soup options: 3 Beef (Beef Noodle, Beef w/ Veg &amp; Barley, Vegetable Beef), 3 Vegetable (Vegetarian Vegetable, Old Fashioned Vegetable, Minestrone). Each shows:</span><span class="co">]</span></span>
<span id="cb1-373"><a href="#cb1-373" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Product (Name &amp; Photo)</span>
<span id="cb1-374"><a href="#cb1-374" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Price ($1.00)</span>
<span id="cb1-375"><a href="#cb1-375" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Serving Size (0.5 cup)</span>
<span id="cb1-376"><a href="#cb1-376" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Calories</span>
<span id="cb1-377"><a href="#cb1-377" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Fats / serving</span>
<span id="cb1-378"><a href="#cb1-378" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Carbohydrates / serving</span>
<span id="cb1-379"><a href="#cb1-379" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Proteins / serving</span>
<span id="cb1-380"><a href="#cb1-380" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Carbon Footprint* / serving (showing g CO2e and equivalent light bulb minutes in a light bulb graphic)</span>
<span id="cb1-381"><a href="#cb1-381" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Carbon Footprint Rating^ / serving (showing a green-to-red scale with a triangle indicating the product's relative footprint)</span>
<span id="cb1-382"><a href="#cb1-382" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-383"><a href="#cb1-383" aria-hidden="true" tabindex="-1"></a>*(Example values from Fig 3 / text for Vegetable Beef Soup: 90 Cal, 1g Fat, 15g Carb, 4g Protein, 1,281g CO2e, 2,127 light bulb minutes)*</span>
<span id="cb1-384"><a href="#cb1-384" aria-hidden="true" tabindex="-1"></a>*(Example values from text for Vegetarian Vegetable Soup: 90 Cal, 0.5g Fat, 18g Carb, 3g Protein, 208g CO2e, 345 light bulb minutes)*</span>
<span id="cb1-385"><a href="#cb1-385" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-386"><a href="#cb1-386" aria-hidden="true" tabindex="-1"></a>*\* The "Carbon Footprint" indicates the total amount of greenhouse gases or their equivalent that were released in order to produce a serving of this food... translated into the number of minutes a 100-watt light bulb would have to be illuminated...*</span>
<span id="cb1-387"><a href="#cb1-387" aria-hidden="true" tabindex="-1"></a>*^ The "Carbon Footprint Rating" provides a visual representation of the carbon footprint of this product compared to other products in the same category...*</span>
<span id="cb1-388"><a href="#cb1-388" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-389"><a href="#cb1-389" aria-hidden="true" tabindex="-1"></a>Which THREE soups will you buy?</span>
<span id="cb1-390"><a href="#cb1-390" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">List of 6 soups</span><span class="co">]</span></span>
<span id="cb1-391"><a href="#cb1-391" aria-hidden="true" tabindex="-1"></a>Please briefly explain why you chose these three soups <span class="sc">\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_</span></span>
<span id="cb1-392"><a href="#cb1-392" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-393"><a href="#cb1-393" aria-hidden="true" tabindex="-1"></a>*Page 3: Food GHG Emissions*</span>
<span id="cb1-394"><a href="#cb1-394" aria-hidden="true" tabindex="-1"></a>Using a 100-watt incandescent light bulb for one hour emits 100 units of greenhouse gas emissions.</span>
<span id="cb1-395"><a href="#cb1-395" aria-hidden="true" tabindex="-1"></a>Using this scale, how many units of greenhouse gas emissions do you think each of the following foods emits to produce and transport?</span>
<span id="cb1-396"><a href="#cb1-396" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Instructions similar to Study 1B</span><span class="co">]</span></span>
<span id="cb1-397"><a href="#cb1-397" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Units of emissions for: Beef soup (half a cup)</span>
<span id="cb1-398"><a href="#cb1-398" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Units of emissions for: Vegetable soup (half a cup)</span>
<span id="cb1-399"><a href="#cb1-399" aria-hidden="true" tabindex="-1"></a>Notes: <span class="co">[</span><span class="ot">Identical to Study 1B Food GHG Notes</span><span class="co">]</span></span>
<span id="cb1-400"><a href="#cb1-400" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-401"><a href="#cb1-401" aria-hidden="true" tabindex="-1"></a>*Page 4: Attention Check Questions*</span>
<span id="cb1-402"><a href="#cb1-402" aria-hidden="true" tabindex="-1"></a>With the following questions, we are interested to know how much you remember from the food choice task that you just completed.</span>
<span id="cb1-403"><a href="#cb1-403" aria-hidden="true" tabindex="-1"></a>Which product were you NOT presented with earlier?</span>
<span id="cb1-404"><a href="#cb1-404" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Bean with Bacon Soup</span>
<span id="cb1-405"><a href="#cb1-405" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Minestrone Soup</span>
<span id="cb1-406"><a href="#cb1-406" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Vegetarian Vegetable Soup</span>
<span id="cb1-407"><a href="#cb1-407" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Beef Noodle Soup</span>
<span id="cb1-408"><a href="#cb1-408" aria-hidden="true" tabindex="-1"></a>How many soups were you presented with?</span>
<span id="cb1-409"><a href="#cb1-409" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>5</span>
<span id="cb1-410"><a href="#cb1-410" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>6</span>
<span id="cb1-411"><a href="#cb1-411" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>7</span>
<span id="cb1-412"><a href="#cb1-412" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>8</span>
<span id="cb1-413"><a href="#cb1-413" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>9</span>
<span id="cb1-414"><a href="#cb1-414" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>10</span>
<span id="cb1-415"><a href="#cb1-415" aria-hidden="true" tabindex="-1"></a>Were you provided with carbon footprint information for each soup?</span>
<span id="cb1-416"><a href="#cb1-416" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>No</span>
<span id="cb1-417"><a href="#cb1-417" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Yes</span>
<span id="cb1-418"><a href="#cb1-418" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-419"><a href="#cb1-419" aria-hidden="true" tabindex="-1"></a>*Page 5: Familiarity*</span>
<span id="cb1-420"><a href="#cb1-420" aria-hidden="true" tabindex="-1"></a>How familiar are you with the soups presented in this study? <span class="co">[</span><span class="ot">Possible responses: “I have never seen this soup before”; “I have seen this soup before but never tasted it”; “I have tasted this soup before"</span><span class="co">]</span></span>
<span id="cb1-421"><a href="#cb1-421" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">List of 6 soups</span><span class="co">]</span></span>
<span id="cb1-422"><a href="#cb1-422" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-423"><a href="#cb1-423" aria-hidden="true" tabindex="-1"></a>*Page 6: Environmental Worldview*</span>
<span id="cb1-424"><a href="#cb1-424" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">NEPr Scale questions - omitted here for brevity</span><span class="co">]</span></span>
<span id="cb1-425"><a href="#cb1-425" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-426"><a href="#cb1-426" aria-hidden="true" tabindex="-1"></a>*Pages 7: Food Choice Questionnaire*</span>
<span id="cb1-427"><a href="#cb1-427" aria-hidden="true" tabindex="-1"></a>It is important to me that the food I eat on a typical day... <span class="co">[</span><span class="ot">all items answered on a 5-point response scale from 1 = “Strongly agree to 5 = “Strongly disagree; subscale has been identified in brackets after each item</span><span class="co">]</span></span>
<span id="cb1-428"><a href="#cb1-428" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">FCQ Items listed covering Health, Mood, Convenience, Sensory appeal, Natural content, Price, Weight control, Familiarity, Animal Welfare, Environmental protection, Political values, Religion - omitted here for brevity</span><span class="co">]</span></span>
<span id="cb1-429"><a href="#cb1-429" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-430"><a href="#cb1-430" aria-hidden="true" tabindex="-1"></a>*Page 8: Demographics*</span>
<span id="cb1-431"><a href="#cb1-431" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Additional Demographics: Diet type (Vegan, Vegetarian, etc.), Dieting Status, Political Affiliation - omitted here for brevity</span><span class="co">]</span></span>
<span id="cb1-432"><a href="#cb1-432" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-433"><a href="#cb1-433" aria-hidden="true" tabindex="-1"></a>*Page 9: Conclusion*</span>
<span id="cb1-434"><a href="#cb1-434" aria-hidden="true" tabindex="-1"></a>Thanks for participating in our study... We will use your responses to help us understand how we can help people make more accurate estimations... Thank you for your participation in this research.</span>
<span id="cb1-435"><a href="#cb1-435" aria-hidden="true" tabindex="-1"></a>If you have any reactions, comments, suggestions... please provide them below. We really do value your feedback! <span class="sc">\_\_\_\_</span></span>
<span id="cb1-436"><a href="#cb1-436" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-437"><a href="#cb1-437" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb1-438"><a href="#cb1-438" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-439"><a href="#cb1-439" aria-hidden="true" tabindex="-1"></a><span class="fu">### Supplementary Note 6: Study 2 - Additional Analyses</span></span>
<span id="cb1-440"><a href="#cb1-440" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-441"><a href="#cb1-441" aria-hidden="true" tabindex="-1"></a>We conducted a regression analysis with group, NEPr, scores from the subscales of the Food Choice Questionnaire (FCQ; health, mood, convenience, sensory appeal, natural content, price, weight control, familiarity, animal welfare, environmental protection, political values, religion <span class="co">[</span><span class="ot">each coded "1" for Strongly Disagree up to “5” for Strongly Agree), and the demographics variables (gender [coded “1” for Man and “2” for Woman</span><span class="co">]</span>, age, race <span class="co">[</span><span class="ot">coded “1” for Caucasian/white, “2” for “African American/black", 3 for Asian/pacific islander, “4” for Hispanic/Latino, “5” for Native American, and “6” for Other</span><span class="co">]</span>, employment status <span class="co">[</span><span class="ot">coded “1” for Employed full time, etc.</span><span class="co">]</span>, education status <span class="co">[</span><span class="ot">coded “1” for Some high school up to “6” for Graduate</span><span class="co">]</span>, political party <span class="co">[</span><span class="ot">coded “1” for Democrat, etc.</span><span class="co">]</span>, household income <span class="co">[</span><span class="ot">coded “0” for $0-9,999 up to "7" for $120,000+</span><span class="co">]</span>, and dietary status <span class="co">[</span><span class="ot">coded “0” for eats red meat and “1” for avoids red meat</span><span class="co">]</span>) entered as predictor variables, and the average number of beef soups purchased as the outcome variable.</span>
<span id="cb1-442"><a href="#cb1-442" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-443"><a href="#cb1-443" aria-hidden="true" tabindex="-1"></a>The analysis revealed a significant effect of group, B = -.49, t(97) = -2.93, p = .004, a significant effect of diet type, B = -1.14, t(97) = -5.038, p &lt; .0001, a significant effect for the political values FCQ subscale, B = -.31, t(97) = -2.181, p = .03, a significant effect for the religion FCQ subscale, B = .25, t(97) = 3.01, p = .03, a significant effect for the environmental protection FCQ subscale, B = .34, t(97) = -2.18, p = .03, and a significant effect of education, B = -.153, t(97) = -2.21, p = .03. In sum, those less likely to purchase cans of beef soup were presented with the GHG emissions information, more educated, have a diet that excluded red meat, and self-reported to choose foods that were aligned with their religious, political, and environmental protection values.</span>
<span id="cb1-444"><a href="#cb1-444" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-445"><a href="#cb1-445" aria-hidden="true" tabindex="-1"></a>We conducted another regression analysis with the same variables entered as predictor variables, and beef-to-vegetable soup GHG emissions ratio purchased as the outcome variable. This analysis once again excluded to two outliers who produced ratios more than six standard deviations from the mean. The analysis revealed a significant effect of group, B = 1.30, t(95) = 3.14, p = .002. No other variables were significant predictors. In sum, those who tended to estimate a higher ratio were presented with the GHG emissions information.</span>
<span id="cb1-446"><a href="#cb1-446" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-447"><a href="#cb1-447" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb1-448"><a href="#cb1-448" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-449"><a href="#cb1-449" aria-hidden="true" tabindex="-1"></a><span class="fu">### Supplementary Note 7: Actual Life-Cycle GHG Emissions for a Range of Prepared Soups</span></span>
<span id="cb1-450"><a href="#cb1-450" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-451"><a href="#cb1-451" aria-hidden="true" tabindex="-1"></a>For Study 2, the actual values of GHG emissions from the life-cycle of different types of vegetable and beef soup were based on data from the website www.eatlowcarbon.org/food-scores, which was last accessed 23 November 2017. According to this website:</span>
<span id="cb1-452"><a href="#cb1-452" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; EatLowCarbon.org was created by Bon Appétit Management Company, a food service pioneer operating hundreds of cafés all over America for corporations, universities, and specialty venues. Bon Appétit is known for tackling pressing social issues such as local food, animal welfare, antibiotics in animal agriculture, farmworker rights, and more. Bon Appétit worked with the nonprofit environmental group Ecotrust to compile and conduct peer-reviewed Life Cycle Assessments from which the information on this site is drawn. Researchers use LCA to calculate the environmental impact of a product's entire life cycle: for food items, that includes the inputs, such as fertilizer, that went into growing it, and the energy that went into transporting, processing and cooking it.</span></span>
<span id="cb1-453"><a href="#cb1-453" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-454"><a href="#cb1-454" aria-hidden="true" tabindex="-1"></a>According to an email correspondence with Bon Appétit:</span>
<span id="cb1-455"><a href="#cb1-455" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; We hired the organization EcoTrust to compile peer reviewed Life Cycle Assessments for single-ingredient foods and combine them according to “recipes” for the dishes shown on the site. That includes the ingredients, how far they traveled (either “domestic” or “international”) and information about how they were cooked.</span></span>
<span id="cb1-456"><a href="#cb1-456" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-457"><a href="#cb1-457" aria-hidden="true" tabindex="-1"></a>The EatLowCarbon.org website listed the following soups:</span>
<span id="cb1-458"><a href="#cb1-458" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Beef Chili Soup – 1,281 grams of CO2e</span>
<span id="cb1-459"><a href="#cb1-459" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Chicken Noodle Soup – 253 grams of CO2e</span>
<span id="cb1-460"><a href="#cb1-460" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Minestrone Soup – 189 grams of CO2e</span>
<span id="cb1-461"><a href="#cb1-461" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Vegetarian Chili – 86 grams of CO2e</span>
<span id="cb1-462"><a href="#cb1-462" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Spinach and Pea Stew – 78 grams of CO2e</span>
<span id="cb1-463"><a href="#cb1-463" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Three Bean Soup – 54 grams of CO2e</span>
<span id="cb1-464"><a href="#cb1-464" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Lentil Soup - 54 grams of CO2e</span>
<span id="cb1-465"><a href="#cb1-465" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-466"><a href="#cb1-466" aria-hidden="true" tabindex="-1"></a>In order to generate the values used in Study 2, we took the value for Beef Chili Soup (1,281 g CO2e) and added/subtracted 10% of it (i.e., 128) to create two new values: 1,153 and 1,409. We then allocated these three values to the three beef soups used in the study:</span>
<span id="cb1-467"><a href="#cb1-467" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Beef Noodle Soup – 1,409 grams of CO2e</span>
<span id="cb1-468"><a href="#cb1-468" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Beef with Vegetables and Barley Soup – 1,153 grams of CO2e</span>
<span id="cb1-469"><a href="#cb1-469" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Vegetable Beef Soup – 1,281 grams of CO2e</span>
<span id="cb1-470"><a href="#cb1-470" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-471"><a href="#cb1-471" aria-hidden="true" tabindex="-1"></a>Similarly, we took the value for Minestrone Soup (189 g CO2e) and added/subtracted 10% of it (i.e., 19) to create two new values: 170 and 208. We then allocated these three values to the three vegetable soups used in the study:</span>
<span id="cb1-472"><a href="#cb1-472" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Vegetarian Vegetable Soup – 208 grams of CO2e</span>
<span id="cb1-473"><a href="#cb1-473" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Old Fashioned Vegetable Soup – 170 grams of CO2e</span>
<span id="cb1-474"><a href="#cb1-474" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>Minestrone Soup – 189 grams of CO2e</span>
<span id="cb1-475"><a href="#cb1-475" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-476"><a href="#cb1-476" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-477"><a href="#cb1-477" aria-hidden="true" tabindex="-1"></a><span class="fu">### References (Supplementary Material)</span></span>
<span id="cb1-478"><a href="#cb1-478" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-479"><a href="#cb1-479" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>Attari, S. Z., DeKay, M. L., Davidson, C. I. &amp; De Bruin, W. B. Public perceptions of energy consumption and savings. *Proceedings of the National Academy of Sciences* **107**, 16054-16059 (2010).</span>
<span id="cb1-480"><a href="#cb1-480" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>Epley, N. &amp; Gilovich, T. The anchoring-and-adjustment heuristic: Why the adjustments are insufficient. *Psychological Science* **17**, 311-318 (2006).</span>
<span id="cb1-481"><a href="#cb1-481" aria-hidden="true" tabindex="-1"></a><span class="ss">3.  </span>U.S. Energy Information Administration (2014). <span class="ot">&lt;http://www.eia.gov/tools/faqs/faq.cfm?id=105&amp;t=3&gt;</span>. Accessed 5 July 2014.</span>
<span id="cb1-482"><a href="#cb1-482" aria-hidden="true" tabindex="-1"></a><span class="ss">4.  </span>United States Environmental Protection Agency (2015) <span class="ot">&lt;https://www.epa.gov/sites/production/files/2015-02/documents/egrid_9th_edition_v1-0_year_2010_ghg_rates.pdf&gt;</span>. Accessed 3 August 2016.</span>
<span id="cb1-483"><a href="#cb1-483" aria-hidden="true" tabindex="-1"></a><span class="ss">5.  </span>Climate Change Connection (2016). <span class="ot">&lt;http://climatechangeconnection.org/emissions/co2-equivalents/&gt;</span>. Accessed 3 August 2016.</span>
<span id="cb1-484"><a href="#cb1-484" aria-hidden="true" tabindex="-1"></a><span class="ss">6.  </span>Alternative Energy Store. (2008). Power ratings (typical) for common appliances. Available at <span class="ot">&lt;http://www.altestore.com/howto/Tools-Calculators-Reference/Reference-Materials/Power-Ratings-typical-for-Common-Appliances/a21/&gt;</span>. Accessed 3 August 2016.</span>
<span id="cb1-485"><a href="#cb1-485" aria-hidden="true" tabindex="-1"></a><span class="ss">7.  </span>Silicon Valley Power. (2015). Appliance energy use chart. Available at <span class="ot">&lt;http://www.siliconvalleypower.com/for-residents/save-energy/appliance-energy-use-chart&gt;</span>. Accessed 3 August 2016.</span>
<span id="cb1-486"><a href="#cb1-486" aria-hidden="true" tabindex="-1"></a><span class="ss">8.  </span>City Water Light &amp; Power. (2015). Appliance energy use chart. Available at <span class="ot">&lt;http://www.cwlp.com/eso/efficiency101/appliancechart.html#chart&gt;</span>. Accessed 3 August 2016.</span>
<span id="cb1-487"><a href="#cb1-487" aria-hidden="true" tabindex="-1"></a><span class="ss">9.  </span>Efficiency Vermont (2015). Electric Usage Chart. Available at <span class="ot">&lt;https://www.efficiencyvermont.com/For-My-Home/ways-to-save-and-rebates/Appliances/Refrigerators/General-Info/Electric-Usage-Chart&gt;</span>. Accessed 3 August 2016.</span>
<span id="cb1-488"><a href="#cb1-488" aria-hidden="true" tabindex="-1"></a><span class="ss">10. </span>Apex Solar (2016). <span class="ot">&lt;http://www.apxsolar.com/downloads/5common_appliance_Wattages_.pdf&gt;</span>. Accessed 3 August 2016.</span>
<span id="cb1-489"><a href="#cb1-489" aria-hidden="true" tabindex="-1"></a><span class="ss">11. </span>Eat For Health (2016). Serving Sizes. Available at: <span class="ot">&lt;https://www.eatforhealth.gov.au/food-essentials/how-much-do-we-need-each-day/serve-sizes/&gt;</span>. Accessed 3 August 2016.</span>
<span id="cb1-490"><a href="#cb1-490" aria-hidden="true" tabindex="-1"></a><span class="ss">12. </span>United States Department of Agriculture (2016). USDA Food Composition Database. <span class="ot">&lt;https://ndb.nal.usda.gov/ndb/foods/&gt;</span>. Accessed 3 August 2016.</span>
<span id="cb1-491"><a href="#cb1-491" aria-hidden="true" tabindex="-1"></a><span class="ss">13. </span>Cordts, A., Nitzko, S. &amp; Spiller, A. Consumer response to negative information on meat consumption in Germany. *International Food and Agribusiness Management Review* **17**, 83-106 (2014).</span>
<span id="cb1-492"><a href="#cb1-492" aria-hidden="true" tabindex="-1"></a><span class="ss">14. </span>Tobler, C., Visschers, V. H. &amp; Siegrist, M. Eating green. Consumers' willingness to adopt ecological food consumption behaviors. *Appetite* **57**, 674-682 (2011).</span></code><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2024 <a href="https://tegorman13.github.io">Thomas Gorman</a></p>
</div>   
    <div class="nav-footer-center">
<p>site made with <a href="https://cran.r-project.org/"><i class="fa-brands fa-r-project" aria-label="r-project"></i></a> and <a href="https://quarto.org/">Quarto</a></p>
</div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://github.com/tegorman13/llm_energy_task" target="_blank">
<p><i class="fa-brands fa-github fa-2.0x" aria-label="github"></i></p>
</a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>